// ============================================================
//  퍼즐 탐험대 · 문제 데이터
//  출처: 최재혁, "퍼즐을 이용한 창의성 교육" (신라대학교, 2013)
//  answerSource: book | derived | book-and-verified
//  * 정답은 별도의 solver(src/verification/*)와 손 풀이로 교차 검증함.
// ============================================================

export const WORLDS = [
  { id: "abstraction", name: "월드 1 · 추상화", emoji: "🔍", color: "w1",
    desc: "필요한 정보 찾기, 규칙 발견, 표·상태·그래프로 단순화하기" },
  { id: "algorithm", name: "월드 2 · 알고리즘", emoji: "⚙️", color: "w2",
    desc: "순서대로 절차 만들기, 순차·선택·반복, 실행하고 고치기" },
  { id: "both", name: "월드 3 · 추상화＋알고리즘", emoji: "🧩", color: "w3",
    desc: "핵심 요소를 뽑아 절차를 설계하고 실행·개선하기" },
];

// 용어 도움말(어려운 말 쉬운 뜻) — 해설에서 처음 나올 때 사용
export const GLOSSARY = {
  "추상화": "문제에서 중요한 특징만 골라 간단하게 나타내는 것",
  "상태": "지금 물체가 놓여 있거나 값이 정해진 모습",
  "알고리즘": "문제를 해결하기 위해 정한 순서",
  "조건": "해결할 때 반드시 지켜야 하는 규칙",
  "반복": "같은 행동을 여러 번 실행하는 것",
  "선택": "조건에 따라 다른 행동을 하는 것",
  "일반화": "찾은 규칙을 다른 경우에도 똑같이 적용하는 것",
  "효율적인 알고리즘": "같은 답을 더 적은 횟수나 더 짧은 시간에 구하는 방법",
};

export const PROBLEMS = [];

// ======================= 월드 1 · 추상화 =======================

PROBLEMS.push({
  id: "A-01", sourceProblem: "4-14", sourcePage: 54, world: "abstraction",
  title: "나는 얼마인가?", engine: "deduce", difficulty: "basic", estimatedMinutes: 5,
  originalProblemText:
    "1. 나는 4자리의 짝수인데 자리수가 모두 다르다.\n2. 자리수를 모두 더하면 10이다.\n3. 모든 자리수는 모두 0보다 크다.\n4. 천과 백의 자리수를 더한 것은 십과 일의 자리수를 더한 것과 같다.\n5. 제일 큰 자리수는 천의 자리수이다.\n나는 얼마인가?",
  studentFriendlyText:
    "네 자리 숫자를 찾아요! 다섯 개의 조건을 모두 지키는 숫자는 딱 하나예요.\n조건 카드를 하나씩 적용하면서, 안 맞는 후보를 지워 보세요.",
  conditions: [
    "① 네 자리 짝수이고, 네 자리의 숫자가 모두 다르다",
    "② 네 자리 숫자를 모두 더하면 10",
    "③ 모든 자리 숫자가 0보다 크다(0이 없다)",
    "④ (천의 자리+백의 자리) = (십의 자리+일의 자리)",
    "⑤ 가장 큰 숫자는 천의 자리에 있다",
  ],
  irrelevantInformation: ["숫자가 '나'라고 불리는 것은 재미를 위한 표현일 뿐, 풀이와 무관"],
  correctAnswers: ["4132"], equivalentAnswers: [],
  config: {
    kind: "deduce",
    candidates: [
      { label: "4132", v: 4132 }, { label: "4312", v: 4312 }, { label: "1432", v: 1432 },
      { label: "3142", v: 3142 }, { label: "2314", v: 2314 }, { label: "1342", v: 1342 },
      { label: "4123", v: 4123 }, { label: "2413", v: 2413 },
    ],
    tests: [
      { text: "조건①: 짝수 & 자리수 모두 다름", fn: (n) => {
          const d = String(n).split("").map(Number);
          return n % 2 === 0 && new Set(d).size === 4; } },
      { text: "조건②: 자리수 합 = 10", fn: (n) => String(n).split("").map(Number).reduce((a,b)=>a+b,0) === 10 },
      { text: "조건③: 0이 없다", fn: (n) => !String(n).includes("0") },
      { text: "조건④: 천+백 = 십+일", fn: (n) => { const d = String(n).split("").map(Number); return d[0]+d[1] === d[2]+d[3]; } },
      { text: "조건⑤: 가장 큰 수가 천의 자리", fn: (n) => { const d = String(n).split("").map(Number); return d[0] === Math.max(...d); } },
    ],
    answerKeys: ["4132"],
  },
  hint1Observation: "먼저 어떤 조건이 후보를 가장 많이 지워줄까요? '짝수'와 '자리수 합 10'을 떠올려 보세요.",
  hint2KeyCondition: "조건 ②(합=10)와 조건 ④(천+백=십+일)를 함께 쓰면, 천+백=5, 십+일=5가 돼요.",
  hint3NextAction: "합이 5가 되는 서로 다른 양수 짝은 (1,4)와 (2,3)뿐이에요. 이 네 숫자(1,2,3,4)로만 만들어 보세요.",
  guidedSolution: [
    "조건②+④를 합치면: (천+백)+(십+일)=10 이고 둘이 같으니 각각 5.",
    "합이 5인 서로 다른 양수 짝은 (1,4),(2,3) 두 가지 → 네 숫자는 1,2,3,4.",
    "조건⑤: 가장 큰 4가 천의 자리 → 천=4, 그래서 백=1(4+1=5).",
    "남은 (2,3)이 십·일. 조건①: 짝수라 일의 자리는 짝수 → 일=2, 십=3.",
    "따라서 4132. 모든 조건에 다시 넣어 확인하면 전부 만족!",
  ],
  fullExplanation: {
    answer: "4132",
    key: "조건 ②와 ④를 합치면 앞 두 자리 합=뒤 두 자리 합=5가 된다는 점.",
    abstraction: "네 자리 숫자를 (천,백,십,일) 네 칸으로 보고, 각 조건을 '식'으로 바꿔 후보를 줄이는 문제로 단순화해요.",
    steps: [
      "합=10, 앞합=뒷합 → 앞합=뒷합=5",
      "합 5인 서로 다른 양수 짝: (1,4),(2,3) → 숫자는 1,2,3,4",
      "제일 큰 4는 천의 자리 → 4_ _ _",
      "천+백=5 → 백=1",
      "짝수 → 일의 자리는 2, 십의 자리는 3",
    ],
    why: [
      "여러 조건을 한꺼번에 쓰면 후보가 확 줄어 계산이 빨라져요(효율적인 알고리즘).",
      "'가장 큰 수가 천의 자리'는 자리를 확정해 주는 강력한 조건이에요.",
    ],
    verify: "4132 → 짝수✓, 네 자리 다름✓, 합 4+1+3+2=10✓, 0없음✓, 4+1=3+2=5✓, 최대 4가 천의 자리✓.",
    mistakes: ["0을 넣어버리는 실수(조건③ 위반)", "짝수 조건을 잊고 일의 자리에 홀수를 두는 실수"],
    failReason: "조건을 하나씩만 따로 보면 후보가 너무 많아 끝까지 못 좁혀요. 조건을 결합해야 해요.",
    better: "모든 4자리 수 9000개를 다 확인(전수조사)해도 되지만, 조건을 결합하면 손으로도 몇 초면 풀려요.",
    other: "네 숫자가 1,2,3,4로 정해진 뒤, 짝수·최대자리 조건으로 배치를 정하는 순서로도 풀 수 있어요.",
    concept: "추상화(중요한 특징만 뽑기), 조건을 이용한 후보 제거, 제약 조건 결합.",
    think: "만약 조건 ⑤가 없었다면 답이 몇 개나 나올까요? 직접 세어 보세요.",
  },
  learningGoals: ["핵심 정보 추출", "제약 조건 결합", "후보 제거"],
  curriculumTags: ["핵심 정보 추출", "문제 분해", "추상화", "패턴과 일반화"],
  reflectionQuestions: ["어떤 조건을 먼저 쓰는 게 가장 효율적이었나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "9000개(1000~9999)의 짝수 전수조사 + 손 풀이",
  verificationEvidence: "전수조사 결과 조건을 모두 만족하는 수는 4132 하나뿐.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["4132(유일)"], optimal: "조건 결합으로 즉시 결정",
    commonWrong: ["1432(최댓값이 천의 자리 아님)", "4312(④ 위반)"],
    wrongWhy: "조건을 개별로만 확인하고 결합/순서를 고려하지 않기 때문.",
    questions: ["조건을 어떤 순서로 적용하면 가장 빨리 풀릴까?", "조건 하나를 빼면 답이 몇 개가 될까?"],
    intro: "여러 단서로 범인을 찾는 '탐정 놀이'로 도입하면 흥미가 높아집니다.",
    group: "모둠별로 조건 카드를 나눠 갖고 한 장씩 공개하며 후보를 지워보게 합니다.",
    tune: "기초: 조건 ①②를 미리 적용해 후보를 4개로 제시. 도전: 조건 ⑤를 빼고 모든 답 찾기.",
    programming: "for 반복 + if 선택으로 전수조사 코드를 작성해 손 풀이와 결과를 비교.",
    extension: ["조건 ⑤ 없이 가능한 모든 답 구하기", "다섯 자리로 확장하기"],
    eval: "필요 조건을 결합해 후보를 줄였는지, 검증 단계를 수행했는지 평가.",
    minutes: 5,
  },
});

PROBLEMS.push({
  id: "A-02", sourceProblem: "4-37", sourcePage: 64, world: "abstraction",
  title: "나이 문제", engine: "deduce", difficulty: "normal", estimatedMinutes: 6,
  originalProblemText:
    "\u201c내 나이의 자리수를 바꾸면 아들 나이가 되지. 지난해엔 내 나이가 아들 나이의 2배였어.\u201d\n이 말을 한 노신사와 아들의 나이는 얼마인가?",
  studentFriendlyText:
    "아버지 나이의 두 자리를 뒤집으면 아들 나이가 돼요. 그리고 '작년'에 아버지 나이는 아들 나이의 딱 2배였어요.\n조건에 맞는 (아버지, 아들) 짝을 찾아보세요.",
  conditions: [
    "① 아버지 나이의 두 자리를 뒤집으면 아들 나이 (예: 73 → 37)",
    "② 작년: (아버지-1) = 2 × (아들-1)",
    "③ 아버지가 아들보다 나이가 많다",
  ],
  irrelevantInformation: ["'노신사'라는 표현은 나이가 많다는 힌트일 뿐 구체 숫자와 무관"],
  correctAnswers: ["아버지 73 / 아들 37"], equivalentAnswers: ["73/37", "73,37"],
  config: {
    kind: "deduce",
    candidates: [
      { label: "아버지 73 / 아들 37", v: { f: 73, s: 37 } },
      { label: "아버지 31 / 아들 13", v: { f: 31, s: 13 } },
      { label: "아버지 52 / 아들 25", v: { f: 52, s: 25 } },
      { label: "아버지 96 / 아들 69", v: { f: 96, s: 69 } },
      { label: "아버지 41 / 아들 14", v: { f: 41, s: 14 } },
      { label: "아버지 84 / 아들 48", v: { f: 84, s: 48 } },
      { label: "아버지 62 / 아들 26", v: { f: 62, s: 26 } },
    ],
    tests: [
      { text: "조건①: 자리 뒤집으면 아들", fn: (v) => Number(String(v.f).split("").reverse().join("")) === v.s },
      { text: "조건③: 아버지 > 아들", fn: (v) => v.f > v.s },
      { text: "조건②: 작년 아버지=2×작년 아들", fn: (v) => (v.f - 1) === 2 * (v.s - 1) },
    ],
    answerKeys: ["아버지 73 / 아들 37"],
  },
  hint1Observation: "'작년에 2배'라는 말에서 아버지의 지금 나이가 홀수인지 짝수인지 생각해 보세요.",
  hint2KeyCondition: "작년: (아버지-1)=2×(아들-1). 그리고 아버지=10a+b, 아들=10b+a로 두면 식이 하나 나와요.",
  hint3NextAction: "식을 정리하면 8a = 19b − 1. b를 1,2,3…로 넣어 정수 a가 나오는 값을 찾아요.",
  guidedSolution: [
    "아버지=10a+b, 아들=10b+a (자리 뒤집기).",
    "작년 조건: (10a+b−1) = 2(10b+a−1) → 8a = 19b − 1.",
    "b=3일 때 8a=56 → a=7. (다른 b는 정수 a가 안 됨)",
    "그래서 아버지=73, 아들=37.",
    "확인: 작년 72 = 2 × 36 ✓.",
  ],
  fullExplanation: {
    answer: "아버지 73세, 아들 37세",
    key: "두 자리 수를 10a+b로 '문자'로 바꾸면 조건이 하나의 식(8a=19b−1)이 된다.",
    abstraction: "나이를 (십의자리 a, 일의자리 b) 두 변수로 표현하고, 문장을 방정식으로 바꾼다.",
    steps: ["아버지=10a+b, 아들=10b+a", "(아버지−1)=2(아들−1) 대입", "8a=19b−1 정리", "정수해 a=7,b=3", "→ 73 / 37"],
    why: ["문장을 식으로 바꾸면 시행착오 없이 정확히 답을 좁힐 수 있어요.", "정수만 가능하다는 성질로 후보가 하나로 줄어요."],
    verify: "73→뒤집으면 37✓, 73>37✓, 작년 72=2×36✓.",
    mistakes: ["'올해 2배'로 잘못 읽기", "자리 뒤집기를 아들이 아니라 아버지에 적용하기"],
    failReason: "문장을 식으로 안 바꾸면 여러 나이를 마구 대입해 시간이 오래 걸려요.",
    better: "두 자리 수(10~99) 전수조사로도 확인 가능하지만, 식으로 풀면 즉시 나옵니다.",
    other: "표를 만들어 아버지 홀수 나이만 훑어보며 찾는 방법(교재 방식)도 있어요.",
    concept: "추상화(수를 변수로), 방정식 모델링, 정수해 탐색.",
    think: "'작년'이 아니라 '재작년에 3배'였다면 답이 어떻게 달라질까요?",
  },
  learningGoals: ["문장을 식으로 바꾸기(모델링)", "정수 조건으로 후보 좁히기"],
  curriculumTags: ["추상화", "모델링", "문제 분해"],
  reflectionQuestions: ["문장을 식으로 바꾼 순간 무엇이 쉬워졌나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "두 자리 수 전수조사(10~99) + 방정식 풀이",
  verificationEvidence: "조건을 모두 만족하는 짝은 (73,37) 하나뿐.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["73/37(유일)"], optimal: "방정식 8a=19b−1의 유일 정수해",
    commonWrong: ["31/13, 52/25 등 '뒤집기'만 만족하는 짝"],
    wrongWhy: "‘작년 2배’ 조건을 대입해 확인하지 않기 때문.",
    questions: ["문장에서 '숨은 조건'은 무엇인가?", "왜 아버지 나이가 홀수여야 할까?"],
    intro: "'수수께끼 대화'를 실감나게 읽어 주며 조건을 하나씩 판서합니다.",
    group: "모둠이 각자 다른 방법(표/식)으로 풀고 어느 쪽이 빠른지 비교.",
    tune: "기초: 후보를 3개로 축소 제시. 도전: 세 자리 나이로 확장.",
    programming: "이중 for + if로 (아버지,아들) 짝을 검사하는 코드 작성.",
    extension: ["세 자리 나이 문제 만들기", "'작년 3배' 변형"],
    eval: "명시 조건과 숨은 조건을 모두 찾아 식으로 표현했는지 평가.",
    minutes: 6,
  },
});

PROBLEMS.push({
  id: "A-03", sourceProblem: "4-51", sourcePage: 69, world: "abstraction",
  title: "외계인의 손가락 수", engine: "base", difficulty: "normal", estimatedMinutes: 6,
  originalProblemText:
    "10진법의 자리값은 100,10,1. 5진법의 자리값은 25,5,1. 우리는 손가락이 10개라 10진법을 쓴다.\n먼 우주의 어떤 나라에서는 이렇게 계산한다.\n  13 + 15 = 31\n  10 × 10 = 100\n  6 × 3 = 24\n외계인의 손가락은 몇 개일까?",
  studentFriendlyText:
    "외계인의 계산이 이상해 보여요! 하지만 사실은 '몇 진법'을 쓰는지만 알면 전부 맞는 계산이에요.\n밑(진법)을 바꿔 보며 세 계산이 모두 맞는 진법을 찾아요. 그 진법의 수가 손가락 개수랍니다.",
  conditions: ["세 계산이 모두 맞아야 함", "진법 b에서 '13'은 b+3, '31'은 3b+1 처럼 자리값으로 해석"],
  irrelevantInformation: ["'외계인'이라는 설정은 재미 요소일 뿐"],
  correctAnswers: ["7"], equivalentAnswers: ["7진법", "손가락 7개"],
  config: {
    kind: "base",
    equations: ["13 + 15 = 31", "10 * 10 = 100", "6 * 3 = 24"],
    bases: [5, 6, 7, 8, 9, 10],
    answerBase: 7,
  },
  hint1Observation: "우리가 아는 10진법이면 13+15=28인데 답이 31이래요. 그럼 자리값이 10이 아니라는 뜻!",
  hint2KeyCondition: "진법을 b라 하면 '13'은 1×b+3, '31'은 3×b+1 이에요.",
  hint3NextAction: "13+15=31 → (b+3)+(b+5) = 3b+1. 이 식을 b에 대해 풀어 보세요.",
  guidedSolution: [
    "진법 b로 보면 13=b+3, 15=b+5, 31=3b+1.",
    "(b+3)+(b+5)=3b+1 → 2b+8=3b+1 → b=7.",
    "확인 10×10=100: 7진법에서 10=7, 7×7=49=100(7) ✓",
    "확인 6×3=24: 18 = 2×7+4 = 24(7) ✓",
    "그러므로 7진법 → 손가락 7개.",
  ],
  fullExplanation: {
    answer: "7 (7진법, 손가락 7개)",
    key: "자리값을 미지수 b로 두면 겉보기 계산이 하나의 방정식이 된다.",
    abstraction: "각 숫자를 'b의 거듭제곱의 합'으로 바꿔 표현(자리값 모델).",
    steps: ["13+15=31 → 2b+8=3b+1 → b=7", "10×10=100 검증", "6×3=24 검증"],
    why: ["한 식으로 b를 정하고, 나머지 식으로 '검증'하면 확신할 수 있어요."],
    verify: "세 식 모두 7진법에서 성립. b=7 유일.",
    mistakes: ["'13'을 십삼(13)으로 읽어버리기", "한 식만 맞춰 보고 끝내기"],
    failReason: "자리값 개념 없이 숫자를 10진수로만 보면 계산이 틀린 것처럼 보여요.",
    better: "b를 2부터 넣어보는 전수 확인도 되지만, 방정식이 훨씬 빨라요.",
    other: "6×3=24로 먼저 b를 구해도 됨: 18=2b+4 → b=7.",
    concept: "진법(자리값), 추상화, 방정식으로 검증.",
    think: "만약 손가락이 8개인 외계인이라면 13+15는 얼마로 적힐까요?",
  },
  learningGoals: ["자리값(진법) 이해", "가설 세우고 검증하기"],
  curriculumTags: ["추상화", "모델링", "패턴과 일반화"],
  reflectionQuestions: ["한 식으로 답을 구하고 다른 식으로 검증한 이유는?"],
  answerSource: "book-and-verified",
  verificationMethod: "진법 5~12 전수 확인 + 방정식",
  verificationEvidence: "세 식을 모두 만족하는 진법은 7뿐.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["7(유일)"], optimal: "방정식으로 즉시",
    commonWrong: ["10(그대로 읽음)", "8, 9(한 식만 확인)"],
    wrongWhy: "자리값 개념 부족, 검증 생략.",
    questions: ["왜 한 식으로 b를 정하고 다른 식으로 확인할까?", "우리 손가락과 진법의 관계는?"],
    intro: "손가락 개수와 진법의 관계(10진법)를 먼저 이야기.",
    group: "모둠별로 서로 다른 진법 나라의 계산표를 만들어 교환하기.",
    tune: "기초: 한 식만 제시. 도전: 두 자리 곱셈이 있는 진법 문제.",
    programming: "parseInt(str, base)로 진법 계산을 검증하는 코드 작성.",
    extension: ["16진법 계산 만들기", "서로 다른 진법 나라 문제 교환"],
    eval: "가설(진법)을 세우고 여러 식으로 검증했는지 평가.",
    minutes: 6,
  },
});

// ---- 그림/비례/패턴 유추 (원본은 그림 문제, 규칙이 분명한 도형으로 재구성) ----
PROBLEMS.push({
  id: "A-04", sourceProblem: "4-54", sourcePage: 70, world: "abstraction",
  title: "그림 유추 · 다른 하나 찾기", engine: "analogy", difficulty: "basic", estimatedMinutes: 4,
  originalProblemText:
    "5개의 그림 중에서 나머지 4개와 가장 적은 공통점을 가진 것은 어느 것인가? 그 이유를 설명하라.",
  studentFriendlyText:
    "다섯 개의 그림이 있어요. 네 개는 어떤 '공통 규칙'을 지키는데, 딱 하나만 규칙을 어겨요.\n색·모양·안쪽 점·개수를 각각 따로 살펴보고, 규칙을 어긴 하나를 고른 뒤 이유를 설명해요.",
  conditions: ["네 그림이 공유하는 공통 특징을 찾는다", "그 특징을 어긴 하나가 정답"],
  irrelevantInformation: ["도형의 절대 크기(살짝 다른 크기)는 규칙과 무관"],
  correctAnswers: ["E"], equivalentAnswers: [],
  config: {
    kind: "analogy", mode: "odd",
    prompt: "네 개는 '테두리 도형 안에 작은 점'이 있어요. 규칙을 어긴 하나를 고르세요.",
    options: [
      { id: "A", shape: { outline: "square", dot: true, fill: "#a5d8ff" } },
      { id: "B", shape: { outline: "triangle", dot: true, fill: "#b2f2bb" } },
      { id: "C", shape: { outline: "circle", dot: true, fill: "#ffec99" } },
      { id: "D", shape: { outline: "pentagon", dot: true, fill: "#d0bfff" } },
      { id: "E", shape: { outline: "square", dot: false, fill: "#ffc9c9" } },
    ],
    answer: "E",
    ruleTags: ["안쪽 점 유무", "테두리 도형", "색"],
  },
  hint1Observation: "각 그림에서 '안쪽에 점이 있는지'를 먼저 확인해 보세요.",
  hint2KeyCondition: "네 그림 모두 안에 작은 점이 있어요. 딱 하나만 점이 없어요.",
  hint3NextAction: "점이 없는 그림을 고르고, 왜 그것이 '다른 하나'인지 말로 설명해 보세요.",
  guidedSolution: [
    "색·모양·점을 각각 따로 살펴요(특징 분리).",
    "색과 모양은 제각각이라 공통 규칙이 아니에요.",
    "'안쪽 점'은 A,B,C,D에 모두 있고 E에만 없어요.",
    "따라서 규칙을 어긴 E가 정답.",
  ],
  fullExplanation: {
    answer: "E (안쪽에 점이 없는 그림)",
    key: "여러 특징(색·모양·점·개수)을 '따로따로' 살펴 공통 규칙을 찾는 것.",
    abstraction: "그림을 (테두리, 색, 점 유무) 같은 '특징 목록'으로 바꿔서 비교.",
    steps: ["특징을 분리: 색/모양/점", "각 특징이 4개에서 공통인지 확인", "점 유무가 공통 규칙", "규칙 어긴 E 선택"],
    why: ["특징을 섞어 보면 헷갈려요. 하나씩 분리하면 규칙이 또렷해져요."],
    verify: "A~D 모두 점 있음, E만 점 없음 → E가 유일하게 규칙을 어김.",
    mistakes: ["색이나 모양이 특이한 것을 답으로 고르기(공통 규칙이 아님)"],
    failReason: "여러 특징을 한꺼번에 보면 '무엇이 공통인지'를 놓쳐요.",
    better: "특징을 표로 만들어 O/X로 적으면 공통 규칙이 바로 보여요.",
    other: "원본 교재 그림은 다른 배치일 수 있어, 규칙이 분명한 도형으로 재구성했어요(교사용 참고).",
    concept: "추상화(특징 추출), 분류, 패턴 인식.",
    think: "만약 '점'이 아니라 '색'이 공통 규칙이라면 답이 어떻게 바뀔까요?",
  },
  learningGoals: ["특징 분리·추출", "공통 규칙 찾기"],
  curriculumTags: ["추상화", "패턴과 일반화", "핵심 정보 추출"],
  reflectionQuestions: ["어떤 특징이 '공통 규칙'이고 어떤 것이 아니었나요?"],
  answerSource: "derived",
  verificationMethod: "특징표(색/모양/점) 작성 후 공통 규칙 확인",
  verificationEvidence: "점 유무만이 4개에서 공통 → 어긴 하나(E)가 유일 정답.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["E"], optimal: "특징표로 즉시",
    commonWrong: ["색이 튀는 그림", "모양이 다른 그림"],
    wrongWhy: "공통이 아닌 특징을 기준으로 삼음.",
    questions: ["어떤 특징이 공통인지 어떻게 확인했나?"],
    intro: "'다른 그림 찾기'를 특징 분리로 접근하도록 안내.",
    group: "모둠이 특징표를 만들어 O/X로 채우기.",
    tune: "기초: 특징 후보 제시. 도전: 두 특징이 동시에 규칙인 그림.",
    programming: "객체 배열의 속성 비교로 '다른 하나'를 찾는 코드.",
    extension: ["학생이 직접 '다른 하나' 문제 만들기"],
    eval: "특징을 분리해 공통 규칙을 명확히 설명했는지 평가.",
    minutes: 4,
    note: "원본은 그림 문제로 정답이 본문에 없음. 규칙(안쪽 점)을 분명히 하여 재구성함.",
  },
});

PROBLEMS.push({
  id: "A-05", sourceProblem: "4-55", sourcePage: 71, world: "abstraction",
  title: "비례 유추 (A:B = C:?)", engine: "analogy", difficulty: "basic", estimatedMinutes: 4,
  originalProblemText: "비례식을 참조하여 '?'에 적합한 그림을 찾아라. (A:B = C:?)",
  studentFriendlyText:
    "왼쪽 규칙을 보세요. A가 B로 변했어요. 똑같은 규칙으로 C가 무엇으로 변할지 골라요.\n(예: 큰 도형 → 작은 도형 이라면, C도 작은 도형이 되어야 해요.)",
  conditions: ["A→B의 변화 규칙을 찾는다", "그 규칙을 C에 똑같이 적용한다"],
  irrelevantInformation: ["도형의 색은 이 문제에서 규칙과 무관"],
  correctAnswers: ["3"], equivalentAnswers: [],
  config: {
    kind: "analogy", mode: "proportion",
    prompt: "규칙: '큰 도형 → 같은 모양의 작은 도형'. 원(큰 원)은 무엇이 될까요?",
    left: { a: { outline: "square", size: 1, fill: "#a5d8ff" }, b: { outline: "square", size: 0.5, fill: "#a5d8ff" } },
    cShape: { outline: "circle", size: 1, fill: "#ffd8a8" },
    options: [
      { id: "1", shape: { outline: "circle", size: 1, fill: "#ffd8a8" } },
      { id: "2", shape: { outline: "square", size: 0.5, fill: "#ffd8a8" } },
      { id: "3", shape: { outline: "circle", size: 0.5, fill: "#ffd8a8" } },
      { id: "4", shape: { outline: "triangle", size: 0.5, fill: "#ffd8a8" } },
    ],
    answer: "3", ruleTags: ["크기 축소", "모양 유지"],
  },
  hint1Observation: "A와 B를 비교해서 '무엇이 달라졌는지' 한 가지만 찾아요.",
  hint2KeyCondition: "모양은 그대로, 크기만 절반으로 줄었어요.",
  hint3NextAction: "원의 모양은 그대로 두고 크기만 절반으로 줄인 그림을 고르세요.",
  guidedSolution: ["A→B 변화: 모양 유지, 크기 절반.", "C(큰 원)에 같은 규칙 적용.", "→ 작은 원(③)."],
  fullExplanation: {
    answer: "③ 작은 원", key: "A→B의 '변화 규칙'을 정확히 한 가지로 뽑아 C에 똑같이 적용.",
    abstraction: "그림을 (모양, 크기) 속성으로 보고, 변한 속성만 골라 규칙화.",
    steps: ["A,B 비교 → 크기만 절반", "모양은 유지", "C=원 → 작은 원"],
    why: ["변한 속성만 정확히 찾으면 엉뚱한 선택지를 걸러낼 수 있어요."],
    verify: "모양(원) 유지 + 크기 절반 → ③만 만족.",
    mistakes: ["모양을 바꿔버리기(사각형·삼각형 선택)", "크기를 그대로 두기(①)"],
    failReason: "변화 규칙을 '크기'가 아닌 다른 것으로 오해하면 틀려요.",
    better: "속성표(모양/크기)를 만들면 규칙이 한눈에 보여요.",
    other: "원본은 정육면체 그림 문제였음(밑면 점). 규칙(크기 축소)을 분명히 하여 재구성.",
    concept: "비례 유추, 속성 기반 추상화.",
    think: "규칙이 '크기'가 아니라 '색'이었다면 답은?",
  },
  learningGoals: ["변화 규칙 추출", "규칙의 일반화 적용"],
  curriculumTags: ["추상화", "패턴과 일반화"],
  reflectionQuestions: ["A→B에서 변한 것과 변하지 않은 것은?"],
  answerSource: "derived",
  verificationMethod: "속성(모양/크기) 비교",
  verificationEvidence: "모양 유지+크기 절반을 만족하는 선택지는 ③뿐.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["③"], optimal: "속성 비교로 즉시",
    commonWrong: ["①(크기 그대로)", "②(모양 바뀜)"], wrongWhy: "변화 규칙 오인.",
    questions: ["변한 속성은 무엇이고 유지된 속성은?"],
    intro: "IQ 검사식 비례 유추를 예로 도입.", group: "모둠이 비례 문제를 직접 출제·교환.",
    tune: "기초: 변화 후보 제시. 도전: 두 속성이 동시에 변하는 문제.",
    programming: "속성 객체의 변환 함수로 규칙 표현.",
    extension: ["색+크기 동시 변화 문제 만들기"],
    eval: "변화 규칙을 한 가지로 명확히 뽑았는지 평가.", minutes: 4,
    note: "그림 문제라 원본에 정답 없음 → 명확한 규칙으로 재구성.",
  },
});

PROBLEMS.push({
  id: "A-06", sourceProblem: "4-56", sourcePage: 71, world: "abstraction",
  title: "패턴 유추 · 다음 그림", engine: "analogy", difficulty: "basic", estimatedMinutes: 4,
  originalProblemText: "왼쪽 그림의 '?'에 해당하는 그림을 찾아라.",
  studentFriendlyText:
    "그림이 일정한 규칙으로 변하고 있어요. 화살표가 조금씩 돌고 있네요!\n다음에 올 그림을 골라요.",
  conditions: ["앞 그림들의 변화 규칙(회전 방향·각도)을 찾는다", "다음 순서의 그림을 예측한다"],
  irrelevantInformation: ["화살표 색은 규칙과 무관"],
  correctAnswers: ["4"], equivalentAnswers: [],
  config: {
    kind: "analogy", mode: "next",
    prompt: "화살표가 시계 방향으로 90°씩 돌아요. 다음(네 번째)에 올 화살표는?",
    series: [
      { outline: "arrow", rotate: 0, fill: "#4dabf7" },
      { outline: "arrow", rotate: 90, fill: "#4dabf7" },
      { outline: "arrow", rotate: 180, fill: "#4dabf7" },
    ],
    options: [
      { id: "1", shape: { outline: "arrow", rotate: 0, fill: "#4dabf7" } },
      { id: "2", shape: { outline: "arrow", rotate: 90, fill: "#4dabf7" } },
      { id: "3", shape: { outline: "arrow", rotate: 180, fill: "#4dabf7" } },
      { id: "4", shape: { outline: "arrow", rotate: 270, fill: "#4dabf7" } },
    ],
    answer: "4", ruleTags: ["회전 90°", "시계 방향"],
  },
  hint1Observation: "첫 번째와 두 번째 화살표의 방향 차이를 각도로 재어 보세요.",
  hint2KeyCondition: "매번 시계 방향으로 90°씩 돌고 있어요(0→90→180).",
  hint3NextAction: "180° 다음은 270°예요. 왼쪽(위)을 가리키는 화살표를 고르세요.",
  guidedSolution: ["변화: 시계방향 90°씩.", "0,90,180 다음은 270.", "→ ④."],
  fullExplanation: {
    answer: "④ (270° 회전)", key: "회전 '방향'과 '각도'를 규칙으로 뽑기.",
    abstraction: "그림을 '회전 각도'라는 숫자 하나로 추상화(0,90,180,…).",
    steps: ["연속 그림의 각도 차이 계산", "규칙: +90°(시계)", "다음 각도 270°"],
    why: ["규칙을 숫자로 바꾸면 다음 값을 계산으로 예측할 수 있어요."],
    verify: "0,90,180,270 → 등차(90). ④만 270°.",
    mistakes: ["회전 방향을 반대로 보기", "각도 규칙 대신 색을 보기"],
    failReason: "규칙을 숫자(각도)로 안 바꾸면 예측이 흔들려요.",
    better: "각도를 수열 0,90,180으로 적어보면 다음 값이 바로 나와요.",
    other: "원본은 그림 문제(가운데 선). 회전 규칙으로 재구성.",
    concept: "패턴 일반화, 그림→수 추상화.",
    think: "만약 60°씩 돈다면 다음은 몇 도일까요?",
  },
  learningGoals: ["회전 규칙 발견", "그림을 수로 추상화"],
  curriculumTags: ["추상화", "패턴과 일반화"],
  reflectionQuestions: ["그림 변화를 어떤 '수'로 바꿔 생각했나요?"],
  answerSource: "derived",
  verificationMethod: "각도 수열화(0,90,180) 후 다음 값 예측",
  verificationEvidence: "등차 90°의 다음은 270° → ④만 일치.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["④"], optimal: "각도 수열로 즉시",
    commonWrong: ["②(반대 회전)", "①"], wrongWhy: "회전 방향/각도 오인.",
    questions: ["그림 변화를 수로 바꾸면 무엇이 쉬워지나?"],
    intro: "시계 바늘의 회전으로 도입.", group: "모둠이 회전 패턴 문제 출제.",
    tune: "기초: 각도 표기. 도전: 회전+색 동시 변화.",
    programming: "각도를 (n×90)%360으로 계산하는 코드.",
    extension: ["두 규칙(회전+크기)이 겹치는 문제"],
    eval: "그림 변화를 수 규칙으로 표현했는지 평가.", minutes: 4,
    note: "그림 문제라 원본 정답 없음 → 회전 규칙으로 재구성.",
  },
});

PROBLEMS.push({
  id: "A-07", sourceProblem: "4-61", sourcePage: 74, world: "abstraction",
  title: "수열 유추", engine: "sequence", difficulty: "normal", estimatedMinutes: 6,
  originalProblemText:
    "'?'에 들어갈 알맞은 수를 유추해 보시오.\n(1) 3, 7, 16, 32, 57, ?\n(2) 1, 1, 2, 4, 7, 13, 24, ?, ?, ?\n(3) O, T, T, F, F, S, S, ?",
  studentFriendlyText:
    "수(또는 글자)가 늘어놓여 있어요. 이웃한 수의 '차이'나 '관계'를 보면 규칙이 보여요.\n규칙을 고르고 다음에 올 수를 예측해 보세요.",
  conditions: ["이웃한 항 사이의 관계(차·합)를 조사한다", "찾은 규칙을 모든 항에 검증한다"],
  irrelevantInformation: [],
  correctAnswers: ["93"], equivalentAnswers: ["93"],
  config: {
    kind: "sequence",
    seq: [3, 7, 16, 32, 57],
    answer: 93,
    ruleOptions: [
      { id: "r1", text: "이웃한 두 수의 차이가 2²,3²,4²,5² … (제곱수)", correct: true },
      { id: "r2", text: "매번 2배씩 커진다", correct: false },
      { id: "r3", text: "매번 5씩 커진다", correct: false },
    ],
    extras: [
      { text: "1,1,2,4,7,13,24,?,?,? (앞 세 수의 합)", answers: [44, 81, 149] },
      { text: "O,T,T,F,F,S,S,? (숫자 One,Two,Three…의 첫 글자)", answers: ["E"] },
    ],
  },
  hint1Observation: "이웃한 두 수의 차이를 차례로 적어 보세요: 4, 9, 16, 25 …",
  hint2KeyCondition: "이웃한 수의 차이가 제곱수(2²,3²,4²,5²)로 커지고 있어요.",
  hint3NextAction: "마지막 수에 '다음 제곱수'만큼을 더하면 돼요. 다음 제곱수가 얼마일지 생각해 보세요.",
  guidedSolution: ["차이: 7−3=4, 16−7=9, 32−16=16, 57−32=25.", "4,9,16,25 = 2²,3²,4²,5².", "다음 차이 6²=36.", "57+36=93."],
  fullExplanation: {
    answer: "93", key: "'값' 자체가 아니라 '이웃한 값의 차이'를 보는 것.",
    abstraction: "수열을 '차이 수열'로 바꿔 규칙을 단순화(계차수열).",
    steps: ["차이 수열 4,9,16,25 계산", "제곱수 규칙 발견", "다음 차이 36", "57+36=93"],
    why: ["차이를 보면 숨은 규칙(제곱수)이 드러나요."],
    verify: "3,7,16,32,57,93의 차이 4,9,16,25,36 = 2²~6² ✓.",
    mistakes: ["2배로 착각(→114)", "차이가 일정하다고 오해"],
    failReason: "값만 보면 규칙이 안 보여요. 차이 수열로 바꿔야 해요.",
    better: "차이의 차이(=3,5,7,9, 등차)까지 보면 더 확실해요.",
    other: "(2)는 앞 세 수의 합(트리보나치): 44,81,149. (3)은 One,Two,…의 첫 글자 → E(ight).",
    concept: "패턴 일반화, 계차수열, 추상화.",
    think: "여러 규칙이 가능해 보일 때, 왜 '가장 단순하고 일관된' 규칙을 고를까요?",
  },
  learningGoals: ["계차수열로 규칙 찾기", "규칙을 모든 항에 검증"],
  curriculumTags: ["추상화", "패턴과 일반화", "모델링"],
  reflectionQuestions: ["차이 수열을 만든 것이 왜 도움이 되었나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "계차수열 계산으로 규칙·다음 값 확인",
  verificationEvidence: "차이 4,9,16,25,36(제곱수) → 다음 항 93. (2),(3)도 규칙으로 검증.",
  teacher: {
    origDifficulty: "레벨 3", allAnswers: ["(1) 93", "(2) 44,81,149", "(3) E"],
    optimal: "계차수열로 즉시", commonWrong: ["114(2배)", "62(+5)"],
    wrongWhy: "값만 보고 차이를 조사하지 않음.",
    questions: ["여러 규칙이 가능할 때 무엇을 기준으로 고를까?", "차이의 차이는 무엇을 알려주나?"],
    intro: "쉬운 등차·등비로 몸풀기 후 계차 개념 도입.",
    group: "모둠이 서로 다른 계차 규칙 수열을 출제.",
    tune: "기초: 차이 수열 힌트 제공. 도전: (2),(3) 포함.",
    programming: "배열의 인접 차를 구하는 반복문 작성.",
    extension: ["피보나치·트리보나치 만들기", "차이의 차이가 일정한 수열 만들기"],
    eval: "규칙을 모든 항에 검증했는지, 다른 규칙 가능성을 언급했는지 평가.", minutes: 6,
  },
});

PROBLEMS.push({
  id: "A-08", sourceProblem: "4-64", sourcePage: 76, world: "abstraction",
  title: "축에는 어떤 수?", engine: "hub", difficulty: "normal", estimatedMinutes: 6,
  originalProblemText:
    "12개의 살과 하나의 축으로 된 바퀴가 있다. 살과 축에 1부터 13까지의 숫자를 하나씩 써넣어, 직선(축을 지나는 지름)에 있는 3개의 숫자 합이 모두 같게 하려 한다. 축에는 얼마를 써넣어야 하는가?",
  studentFriendlyText:
    "바퀴에 살 12개와 가운데 축 1개가 있어요. 1~13을 한 번씩 써넣어요.\n축을 지나는 6개의 지름(양쪽 살 2개 + 축 = 3칸)의 합이 모두 같아야 해요. 축에 올 수 있는 수를 골라요!",
  conditions: ["1~13을 한 번씩 사용", "지름 6개의 (살+축+살) 합이 모두 같음", "축은 6개 지름에 공통으로 포함"],
  irrelevantInformation: ["살의 물리적 길이·색은 무관"],
  correctAnswers: ["7"], equivalentAnswers: ["1", "13"],
  config: {
    kind: "hub", spokes: 12, min: 1, max: 13,
    options: [1, 7, 13, 6, 8, 4], acceptable: [1, 7, 13], elegant: 7,
  },
  hint1Observation: "축의 수는 6개의 지름 모두에 들어가요. 전체 합과 어떤 관계가 있을까요?",
  hint2KeyCondition: "1~13의 합은 91. 6개 지름 합의 총합 = (살 합) + 6×축 = (91−축) + 6×축 = 91 + 5×축.",
  hint3NextAction: "6×(한 지름 합) = 91 + 5×축 이 정수가 되려면 축이 어떤 수여야 할까요? (91+5×축이 6의 배수)",
  guidedSolution: [
    "1~13 합 = 91.",
    "지름 6개 합의 총합 = 살 전체(91−축) + 축을 6번 = 91 + 5×축.",
    "이것이 6×(공통합)이어야 하므로 91+5×축은 6의 배수.",
    "축=1,7,13일 때 성립(합=16,21,26).",
    "각 경우 남은 12수를 '합이 일정'한 6쌍으로 실제로 짝지을 수 있어 모두 가능(대표 답 7).",
  ],
  fullExplanation: {
    answer: "7 (또한 1, 13도 가능 — 조건을 만족하는 모든 답 인정)",
    key: "축은 6개 지름에 공통으로 5번 '더' 들어간다는 점(91+5×축).",
    abstraction: "바퀴를 '6개의 지름 = 살2+축' 식으로 표현하고, 전체 합으로 축을 제약.",
    steps: ["전체합 91", "총합 = 91+5×축 = 6×공통합", "6의 배수 조건 → 축∈{1,7,13}", "각 경우 6쌍 짝짓기 가능 확인"],
    why: ["공통 요소(축)가 합에 몇 번 들어가는지 세면 축을 바로 좁힐 수 있어요."],
    verify: "축=7: 남은 수를 (1,13)(2,12)(3,11)(4,10)(5,9)(6,8)로 짝지으면 각 지름합 21. 축=1,13도 각각 15,13 짝짓기 가능.",
    mistakes: ["축을 한 번만 세고 6번 들어가는 걸 놓치기", "정수 조건을 확인 안 하기"],
    failReason: "무작정 숫자를 채워 넣으면 경우가 너무 많아 헤매요.",
    better: "합으로 축을 먼저 정하면(1,7,13) 나머지는 쌍 맞추기만 하면 돼요.",
    other: "교재는 레벨1로 '가운데 수 7'을 의도했지만, 수학적으로 1,13도 성립 → 모두 정답 인정.",
    concept: "추상화(공통 요소 세기), 합의 보존, 일반화.",
    think: "왜 축이 1,7,13처럼 '6으로 나눈 나머지가 1'인 수여야 할까요?",
  },
  learningGoals: ["공통 요소가 합에 미치는 영향 분석", "불필요한 계산 줄이기"],
  curriculumTags: ["추상화", "모델링", "패턴과 일반화"],
  reflectionQuestions: ["축의 역할을 한 문장으로 설명해 보세요."],
  answerSource: "book-and-verified",
  verificationMethod: "전체 합 논리 + 12수 쌍짝짓기 존재성 확인(솔버)",
  verificationEvidence: "축∈{1,7,13} 각각에 대해 합 일정한 6쌍 짝짓기가 실제로 존재. 그 외 값은 6배수 조건 불만족.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["1, 7, 13 (모두 성립, 대표 7)"],
    optimal: "합 논리로 축을 세 개로 좁힌 뒤 존재성 확인",
    commonWrong: ["6, 8 등(6배수 조건 불만족)"], wrongWhy: "축이 여러 번 더해지는 것을 반영 못함.",
    questions: ["축은 합에 몇 번 들어가나?", "왜 6의 배수 조건이 나올까?"],
    intro: "자전거 바퀴 사진으로 지름·축 개념 도입.",
    group: "모둠이 축을 1/7/13로 나눠 실제로 채워보고 발표.",
    tune: "기초: 살 6개(지름3)로 축소. 도전: 모든 가능한 축과 그 이유 설명.",
    programming: "1~13 순열/짝짓기 탐색으로 가능한 축을 찾는 코드.",
    extension: ["살 6개 바퀴로 일반화", "'왜 나머지 1인가' 증명해 보기"],
    eval: "공통 요소 분석으로 불필요한 계산을 줄였는지, 여러 답을 인정했는지 평가.", minutes: 6,
  },
});

// ======================= 월드 2 · 알고리즘 =======================

PROBLEMS.push({
  id: "B-01", sourceProblem: "5-1", sourcePage: 84, world: "algorithm",
  title: "3·5·8 물항아리", engine: "waterjug", difficulty: "normal", estimatedMinutes: 8,
  originalProblemText:
    "탁자 위에 3ℓ,5ℓ,8ℓ 물항아리가 있다. 3ℓ와 5ℓ는 비어 있고 8ℓ는 가득 찼다. 최소 몇 번 물을 부으면 5ℓ와 8ℓ 항아리에 각각 4ℓ의 물을 채울 수 있는가? (부을 때는 받는 항아리가 가득 차거나, 주는 항아리가 빌 때까지 붓는다)",
  studentFriendlyText:
    "8ℓ 항아리에 물 8ℓ가 가득 있어요. 3ℓ·5ℓ 항아리로 옮겨 부어서\n8ℓ 항아리와 5ℓ 항아리에 각각 정확히 4ℓ를 만들어요. 되도록 적은 횟수로!",
  conditions: ["항아리 용량 8,5,3", "붓기는 '가득 채우거나' 또는 '완전히 비울 때'까지", "목표: 8ℓ=4, 5ℓ=4, 3ℓ=0"],
  irrelevantInformation: ["항아리의 재질·모양은 무관"],
  correctAnswers: ["7"], equivalentAnswers: ["7번", "7회"],
  config: {
    kind: "waterjug",
    caps: [8, 5, 3], start: [8, 0, 0], goal: [4, 4, 0],
    labels: ["8ℓ", "5ℓ", "3ℓ"], minPours: 7,
  },
  hint1Observation: "최종 목표(4,4,0)에 가까워지려면 '4ℓ'를 어떻게 만들까요? 3ℓ 항아리가 힌트예요.",
  hint2KeyCondition: "3ℓ 항아리가 있으니, 다른 항아리에 1ℓ만 있으면 4ℓ는 금방 만들어요(한 수 앞 내다보기).",
  hint3NextAction: "8ℓ를 5ℓ 쪽으로 먼저 붓는 방법과 3ℓ 쪽으로 먼저 붓는 방법을 각각 시도해, 더 적은 쪽을 찾아보세요.",
  guidedSolution: [
    "8→5 (8:3, 5:5, 3:0)", "5→3 (8:3, 5:2, 3:3)", "3→8 (8:6, 5:2, 3:0)",
    "5→3 (8:6, 5:0, 3:2)", "8→5 (8:1, 5:5, 3:2)", "5→3 (8:1, 5:4, 3:3)", "3→8 (8:4, 5:4, 3:0) ✅ 7번",
  ],
  fullExplanation: {
    answer: "최소 7번 (8→5 먼저 붓는 방법)",
    key: "상태를 (8ℓ,5ℓ,3ℓ) 세 수의 묶음으로 표시하고, 붓기를 상태 변화로 보는 것.",
    abstraction: "각 순간을 (a,b,c) 상태로 추상화 → 붓기는 상태→상태 이동(상태 그래프).",
    steps: ["목표 4ℓ = '1ℓ + 3ℓ'로 분해", "8→5 우선 전략으로 붓기", "7번 만에 (4,4,0) 도달"],
    why: ["'한 수 앞'을 내다보면(1ℓ 만들기) 헤매지 않고 최단 경로로 가요.", "두 방법(8→3 먼저=8번, 8→5 먼저=7번)을 비교해 더 적은 쪽을 고름."],
    verify: "너비 우선 탐색(BFS)으로 (8,0,0)→(4,4,0) 최단 = 7번임을 확인.",
    mistakes: ["아무렇게나 부어 우연히 맞히기", "붓기 규칙(가득/완전히)을 어기기"],
    failReason: "전략 없이 부으면 8번 이상 걸리거나 같은 상태를 반복해요.",
    better: "8→3 먼저 방법은 8번. 8→5 먼저가 7번으로 더 효율적.",
    other: "BFS로 모든 상태를 탐색하면 최단 경로를 보장할 수 있어요(프로그램).",
    concept: "상태 표현, 상태 그래프, 최단 경로(BFS), 효율 비교.",
    think: "8→3 먼저 방법은 왜 한 번 더 걸릴까요?",
  },
  learningGoals: ["상태를 수의 묶음으로 표현", "최소 횟수 탐색", "두 전략의 효율 비교"],
  curriculumTags: ["상태 표현", "알고리즘 설계", "반복 구조", "효율성 비교"],
  reflectionQuestions: ["'한 수 앞 내다보기'가 왜 도움이 되었나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "BFS 최단 경로 탐색(src/verification/waterJugSolver)",
  verificationEvidence: "BFS 결과 (8,0,0)→(4,4,0) 최소 7회. 교재의 두 방법(8,7) 중 7이 최소.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["최소 7번(경로는 여러 개 가능)"], optimal: "7회",
    commonWrong: ["8번(8→3 먼저)", "붓기 규칙 위반"], wrongWhy: "전략 부재·규칙 오해.",
    questions: ["상태를 어떻게 표기하면 편할까?", "왜 8→5가 더 빠를까?"],
    intro: "실제 컵으로 시연 후 상태 표기법 소개.",
    group: "모둠이 8→3, 8→5 방법을 각각 맡아 횟수 비교.",
    tune: "기초: 목표를 5ℓ에 4ℓ만. 도전: 임의 용량으로 일반화(최대공약수).",
    programming: "BFS로 상태 그래프를 탐색하는 코드 작성.",
    extension: ["9·4·∞ 등 다른 용량", "gcd로 도달 가능성 판단"],
    eval: "상태 표현·최소 횟수·전략 비교를 수행했는지 평가.", minutes: 8,
  },
});

PROBLEMS.push({
  id: "B-02", sourceProblem: "5-6", sourcePage: 87, world: "algorithm",
  title: "7분·11분 모래시계", engine: "orderSteps", difficulty: "basic", estimatedMinutes: 6,
  originalProblemText:
    "7분과 11분을 잴 수 있는 두 개의 모래시계로 15분이 걸리는 달걀 요리를 하려면 모래시계를 어떻게 뒤집으면 되는지 그 절차를 적으시오. (모래는 아래에만 있고 뒤집는 시간은 무시, 연속 15분을 재야 함)",
  studentFriendlyText:
    "7분·11분 모래시계로 정확히 15분을 재고 싶어요. 행동 카드를 올바른 순서로 배열해 제출해 보세요!",
  conditions: ["두 시계는 7분·11분", "연속으로 15분을 재야 함", "뒤집는 시간은 0"],
  irrelevantInformation: ["달걀 개수는 무관"],
  correctAnswers: ["동시뒤집기 → 7분끝(요리시작) → 11분끝(11분 뒤집기) → 11분끝(요리끝)"], equivalentAnswers: [],
  config: {
    kind: "orderSteps",
    steps: [
      { id: 0, text: "① 7분·11분 모래시계를 동시에 뒤집는다 (요리 준비)" },
      { id: 1, text: "② 7분 모래시계가 끝나면 요리를 시작한다 (여기부터 시간 재기)" },
      { id: 2, text: "③ 11분 모래시계가 끝나면 바로 11분을 다시 뒤집는다" },
      { id: 3, text: "④ 다시 11분이 끝나면 요리를 끝낸다 (요리 시작부터 15분)" },
    ],
    correctOrder: [0, 1, 2, 3],
    timeline: "요리 시작 t=7분, 11분을 t=11에 다시 뒤집어 t=22에 끝 → 22−7 = 15분",
  },
  hint1Observation: "두 시계를 동시에 뒤집으면, 한 시계가 먼저 끝나요. 그 '시간 차이'가 몇 분일까요?",
  hint2KeyCondition: "11분 − 7분 = 4분. 이 4분이 열쇠예요!",
  hint3NextAction: "한 시계가 끝나는 '순간'을 기준으로 삼고, 남은 시계를 한 번 더 활용할 수 있는지 생각해 보세요.",
  guidedSolution: [
    "동시에 뒤집기(t=0).", "7분 끝(t=7) → 요리 시작.",
    "11분 끝(t=11) → 11분 다시 뒤집기.", "11분 다시 끝(t=22) → 요리 끝. 22−7=15분.",
  ],
  fullExplanation: {
    answer: "동시 뒤집기 → (7분 끝)요리 시작 → (11분 끝)11분 재뒤집기 → (11분 끝)요리 끝 = 15분",
    key: "15 = 11 + (11 − 7). 두 시계의 '차이 4분'을 이용.",
    abstraction: "각 시계를 '남은 시간'으로 보고, 사건(끝남) 시점을 수직선 위 시각으로 표현.",
    steps: ["동시 시작", "7분 시점부터 계측", "11분을 한 번 더 사용", "총 22−7=15분"],
    why: ["뒤집는 순서를 바꾸면 재는 시간이 달라져요. 순서가 곧 알고리즘이에요."],
    verify: "요리 시작 t=7, 끝 t=22 → 정확히 15분 연속.",
    mistakes: ["요리 시작 시점을 t=0으로 잡기", "11분을 다시 뒤집는 단계를 빼먹기"],
    failReason: "순서가 틀리면 4분이나 8분처럼 다른 시간이 재져요.",
    better: "'차이(11−7=4)'를 먼저 떠올리면 순서가 자연스럽게 정해져요.",
    other: "0분부터 재고 싶다면 다른 조합(예: 두 시계로 4분 먼저 만들기)도 가능.",
    concept: "순차 구조, 절차(알고리즘) 설계, 사건 기반 시간 모델.",
    think: "5분·7분 시계로 11분을 재려면 순서를 어떻게 짜야 할까요?",
  },
  learningGoals: ["절차를 순서대로 표현", "시간 차이를 이용한 설계"],
  curriculumTags: ["알고리즘 설계", "순차 구조", "알고리즘 실행"],
  reflectionQuestions: ["순서를 바꾸면 결과가 왜 달라질까요?"],
  answerSource: "book-and-verified",
  verificationMethod: "사건 시각 시뮬레이션(t=0,7,11,22)으로 15분 확인",
  verificationEvidence: "요리 구간 [7,22] 길이 = 15분. 교재 절차와 일치.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["위 순서(대표). 다른 유효 순서도 가능"], optimal: "모래시계 뒤집기 2회",
    commonWrong: ["t=0부터 계측", "11분 재뒤집기 누락"], wrongWhy: "계측 시작 시점 오해.",
    questions: ["두 시계의 차이는 왜 중요한가?", "순서와 알고리즘의 관계는?"],
    intro: "요리 타이머 이야기로 흥미 유발.",
    group: "모둠이 카드로 순서를 맞추고 수직선에 사건을 표시.",
    tune: "기초: 카드 2장 고정. 도전: 5·7시계로 11분.",
    programming: "사건 큐로 모래시계를 시뮬레이션하는 코드.",
    extension: ["4·7시계로 9분", "임의 a·b로 잴 수 있는 시간 탐구"],
    eval: "절차를 순서대로 정확히 구성하고 시간을 계산했는지 평가.", minutes: 6,
  },
});

PROBLEMS.push({
  id: "B-03", sourceProblem: "5-10", sourcePage: 90, world: "algorithm",
  title: "모빌 기초 (평형 맞추기)", engine: "mobile", difficulty: "basic", estimatedMinutes: 5,
  originalProblemText:
    "모빌이 평형을 이루려면 받침점에 작용하는 힘이 왼쪽과 오른쪽이 같아야 한다. 힘 = 거리 × 추의 무게. '?' 추의 무게는 몇 그램인가?",
  studentFriendlyText:
    "모빌은 '거리 × 무게'가 왼쪽·오른쪽 같아야 평형이 돼요.\n'?' 자리에 알맞은 추(그램)를 골라 모빌을 수평으로 만들어요!",
  conditions: ["힘 = 거리 × 무게", "왼쪽 힘 = 오른쪽 힘이면 평형"],
  irrelevantInformation: ["추의 색·모양은 무관"],
  correctAnswers: ["6"], equivalentAnswers: ["6그램"],
  config: {
    kind: "mobile",
    // 한 단 모빌: 왼쪽 거리2·무게3, 오른쪽 거리1·무게?  → 2*3 = 1*?  → ?=6
    tree: { type: "bar",
      left: { dist: 2, node: { type: "leaf", w: 3 } },
      right: { dist: 1, node: { type: "leaf", w: null, unknown: true } } },
    options: [3, 4, 5, 6, 7], answer: 6,
  },
  hint1Observation: "왼쪽의 '거리 × 무게'를 먼저 계산해 보세요.",
  hint2KeyCondition: "왼쪽 = 2 × 3 = 6. 오른쪽도 6이 되어야 해요.",
  hint3NextAction: "오른쪽은 거리 1이니까, 무게 × 1 = 6 → 무게는?",
  guidedSolution: ["왼쪽 힘 = 2×3 = 6.", "오른쪽 힘 = 1×? = 6.", "따라서 ? = 6그램."],
  fullExplanation: {
    answer: "6그램", key: "힘(돌림힘) = 거리 × 무게, 양쪽이 같아야 평형.",
    abstraction: "모빌을 '거리×무게' 값(모멘트)으로 바꿔 등식으로 표현.",
    steps: ["왼쪽 2×3=6", "오른쪽 1×?=6", "?=6"],
    why: ["물리 상황을 곱셈식으로 바꾸면 미지수를 바로 구할 수 있어요."],
    verify: "왼쪽 6 = 오른쪽 1×6 = 6 ✓ 평형.",
    mistakes: ["거리와 무게를 더하기", "거리를 무시하고 무게만 비교"],
    failReason: "'거리×무게'가 아니라 무게만 맞추면 기울어져요.",
    better: "양쪽 힘을 먼저 계산해 등식을 세우면 즉시 답.",
    other: "여러 추가 걸린 경우엔 각 힘을 모두 더해 비교.",
    concept: "모델링(곱셈식), 등식, 균형.",
    think: "거리를 2배로 늘리면 무게는 어떻게 바뀌어야 할까요?",
  },
  learningGoals: ["곱셈식 모델링", "균형 조건 이해"],
  curriculumTags: ["모델링", "추상화", "알고리즘 실행"],
  reflectionQuestions: ["왜 무게만이 아니라 거리도 곱해야 하나요?"],
  answerSource: "derived",
  verificationMethod: "모멘트 등식 계산(솔버로 트리 평형 확인)",
  verificationEvidence: "2×3 = 1×6 = 6 → 평형. ?=6 유일. (교재 5-10의 원리를 사용한 재구성 도형)",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["6"], optimal: "등식으로 즉시",
    commonWrong: ["3(무게만 맞춤)", "5"], wrongWhy: "거리 요소 누락.",
    questions: ["힘은 무엇으로 정해지나?"],
    intro: "실제 옷걸이 모빌로 시연.", group: "모둠이 추를 바꿔가며 평형 실험.",
    tune: "기초: 거리 1로 고정. 도전: 여러 추 동시.",
    programming: "트리 순회로 각 힘을 합산·비교하는 코드.",
    extension: ["여러 추가 걸린 팔", "삼단 모빌"],
    eval: "거리×무게 개념으로 균형식을 세웠는지 평가.", minutes: 5,
    note: "교재 5-10은 그림 문제(원문 예시 답=3g)였음. 본 스테이지는 같은 원리(거리×무게)로 만든 한 단 모빌(정답 6g)로 재구성함.",
  },
});

PROBLEMS.push({
  id: "B-04", sourceProblem: "5-12", sourcePage: 91, world: "algorithm",
  title: "이단 모빌", engine: "mobile", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "추를 걸 수 있는 곳이 두 개의 단(이단)이다. 아래 단도 평형을 이루고 위의 단도 평형을 이루어야 한다. 아래 단이 위 단에 거는 힘은 아래 단 추 무게의 합과 같다. '?'에는 몇 그램 추를 걸어야 하는가?",
  studentFriendlyText:
    "두 층짜리 모빌이에요! 아래층도 평형, 위층도 평형이어야 해요.\n아래층부터 차근차근 계산해서 '?' 추를 골라 보세요.",
  conditions: ["각 단이 따로 평형", "아래 단이 위에 거는 무게 = 아래 단 추 무게의 합", "힘 = 거리 × 무게"],
  irrelevantInformation: [],
  correctAnswers: ["4"], equivalentAnswers: ["4그램"],
  config: {
    kind: "mobile",
    // 위 단: 왼쪽 거리3·무게2, 오른쪽 거리1·(아래 단)
    // 아래 단: 왼쪽 거리1·무게?, 오른쪽 거리2·무게2  → 1*? = 2*2 → ?=4, 합=6
    // 위 단: 3*2=6 = 1*6 ✓
    tree: { type: "bar",
      left: { dist: 3, node: { type: "leaf", w: 2 } },
      right: { dist: 1, node: { type: "bar",
        left: { dist: 1, node: { type: "leaf", w: null, unknown: true } },
        right: { dist: 2, node: { type: "leaf", w: 2 } } } } },
    options: [2, 3, 4, 5], answer: 4,
  },
  hint1Observation: "이단 모빌은 '아래층부터' 푸는 게 편해요. 아래층 오른쪽 힘을 먼저 구해요.",
  hint2KeyCondition: "아래층: 왼쪽 1×? = 오른쪽 2×2 = 4 → ?=4. 그러면 아래층 무게 합 = ?+2.",
  hint3NextAction: "?=4면 아래층 합 = 6. 위층: 3×2 = 1×6 = 6 → 평형! 확인해 보세요.",
  guidedSolution: [
    "아래층 균형: 1×? = 2×2 = 4 → ? = 4.", "아래층 무게 합 = 4+2 = 6.",
    "위층 오른쪽에는 이 6이 거리 1로 걸림 → 1×6 = 6.", "위층 왼쪽 3×2 = 6 → 평형 ✅.",
  ],
  fullExplanation: {
    answer: "4그램", key: "아래 단부터 풀고, 그 합을 위 단의 무게로 올려 쓰는 '아래→위' 순서.",
    abstraction: "모빌을 트리로 보고, 잎(추)부터 위로 힘을 합산(재귀/후위 순회).",
    steps: ["아래층 1×?=2×2 → ?=4", "아래층 합=6", "위층 3×2 = 1×6 확인"],
    why: ["아래층 무게 합이 정해져야 위층을 계산할 수 있어요(계산 순서=아래→위)."],
    verify: "아래층 1×4 = 2×2 = 4 ✓, 위층 3×2 = 1×(4+2) = 6 ✓.",
    mistakes: ["위층부터 풀려다 아래층 합을 몰라 막힘", "아래층 합을 빼먹고 추 하나만 올리기"],
    failReason: "계산 순서를 위→아래로 하면 필요한 값을 아직 몰라 막혀요.",
    better: "잎부터 계산(후위 순회)하면 한 번에 위로 올라가며 풀려요.",
    other: "여러 층이면 같은 방법을 반복(재귀).",
    concept: "트리 구조, 후위 순회, 부분 문제 해결.",
    think: "왜 위층이 아니라 아래층부터 계산해야 할까요?",
  },
  learningGoals: ["부분 문제(아래층)부터 해결", "계산 순서 설계"],
  curriculumTags: ["문제 분해", "모델링", "알고리즘 설계", "반복 구조"],
  reflectionQuestions: ["계산 순서를 어떻게 정했나요?"],
  answerSource: "derived",
  verificationMethod: "트리 평형 솔버로 모든 단 균형 확인",
  verificationEvidence: "아래층(1×4=2×2)·위층(3×2=1×6) 모두 평형. ?=4 유일. (교재 5-12 원리 기반 재구성)",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["4"], optimal: "아래→위 순서로 계산",
    commonWrong: ["2(아래층 합 미반영)"], wrongWhy: "계산 순서 오류.",
    questions: ["아래층 합은 위층에서 어떤 역할을 하나?"],
    intro: "이단 옷걸이 모빌 시연.", group: "모둠이 층별로 나눠 계산 후 합치기.",
    tune: "기초: 아래층만. 도전: 삼단 모빌.",
    programming: "재귀로 트리의 무게 합·평형을 계산.",
    extension: ["삼단·오단 모빌", "1~n 추로 평형 만들기"],
    eval: "아래층부터의 계산 순서를 설계했는지 평가.", minutes: 7,
    note: "교재 5-12는 그림 문제. 같은 원리(아래 단이 위 단에 거는 힘=아래 추 무게 합)로 만든 이단 모빌(정답 4g)로 재구성함.",
  },
});

PROBLEMS.push({
  id: "B-05", sourceProblem: "5-18", sourcePage: 95, world: "algorithm",
  title: "9개의 동전", engine: "balance", difficulty: "basic", estimatedMinutes: 6,
  originalProblemText:
    "9개의 동전 중 무게가 다른 한 개가 있다. 양팔 저울을 사용해 무게가 다른 동전을 찾아라. (예: (1,2,3)과 (4,5,6)을 재면 왼쪽이 올라가고, (1,2,3)과 (7,8,9)는 평형, (4)와 (5)도 평형 → 6번이 다른 동전)",
  studentFriendlyText:
    "9개의 동전 중 하나만 무게가 달라요. 양팔 저울에 동전을 올려 기울기를 보고,\n무게가 다른 동전을 최소 횟수로 찾아요! (3개씩 세 묶음으로 나누는 게 열쇠)",
  conditions: ["동전 9개, 그중 1개만 무게가 다름", "양팔 저울로 비교(왼쪽 무거움/오른쪽 무거움/평형)"],
  irrelevantInformation: ["동전의 그림·연도는 무관"],
  correctAnswers: ["6"], equivalentAnswers: ["6번 동전"],
  config: {
    kind: "balance", n: 9, oddIndex: 6, heavier: true, unknownDir: true,
    maxWeighings: 3, optimalWeighings: 3,
  },
  hint1Observation: "9개를 어떻게 '똑같은 크기의 묶음'으로 나누면 한 번에 많이 알 수 있을까요?",
  hint2KeyCondition: "3개씩 세 묶음! 두 묶음을 저울에 올리면, 다른 동전이 어느 묶음인지 한 번에 알아요.",
  hint3NextAction: "저울이 기울면 '무거운 쪽에 무거운 동전' 또는 '가벼운 쪽에 가벼운 동전' 두 경우가 남아요. 이를 갈라낼 다음 저울질을 생각해 보세요.",
  guidedSolution: [
    "9개를 (1,2,3)(4,5,6)(7,8,9) 세 묶음으로 나눈다.",
    "1차: (1,2,3) vs (4,5,6) → 왼쪽이 올라감. (아직 무거운지 가벼운지 모름: (4,5,6)에 무거운 것 또는 (1,2,3)에 가벼운 것)",
    "2차: (1,2,3) vs (7,8,9) → 평형. 따라서 (1,2,3)은 정상 → (4,5,6)에 '무거운' 동전이 있음이 확정.",
    "3차: (4) vs (5) → 평형 → 6번이 무거운 동전.",
    "→ 무게 방향을 몰랐기 때문에 교재 풀이는 저울질 3번을 사용한다.",
  ],
  fullExplanation: {
    answer: "다른 동전 = 6번 (무거운 쪽)",
    key: "무게가 '무거운지 가벼운지 모른다'는 점 — 그래서 방향까지 가려내야 한다.",
    abstraction: "동전 묶음을 '후보 집합'으로 보고, 저울 결과(좌/우/평형)로 집합과 방향을 좁히는 문제.",
    steps: ["3묶음으로 분할", "1차로 범인 묶음 후보를 좁힘", "2차로 정상 묶음을 확인해 방향 확정", "3차로 묶음 안 1개 결정 → 6번"],
    why: ["저울 결과는 3가지라 3등분이 효율적.", "방향을 모르면 한 번의 저울질로 '무겁다/가볍다' 두 경우가 함께 생겨 저울질이 한 번 더 필요."],
    verify: "(1,2,3)<(4,5,6), (1,2,3)=(7,8,9) → (4,5,6)에 무거운 것. (4)=(5) → 6번. 교재와 동일하게 저울질 3번.",
    mistakes: ["방향(무겁/가벼움)을 모르는데 2번 만에 끝난다고 단정", "평형 결과의 의미(둘 다 정상)를 놓치기"],
    failReason: "방향을 모르는 9개에서 2번만 재면, 첫 저울질이 기울었을 때 남는 6가지 경우를 한 번에 못 가려요.",
    better: "만약 '가볍다/무겁다'를 미리 안다면 3등분으로 9→3→1, 즉 2번이면 충분(→ B-06). 방향을 모르면 최소 3번.",
    other: "일반적으로 방향을 모를 때 k번으로 판별 가능한 최대 동전 수는 (3ᵏ−3)/2 (k=2→3개, k=3→12개).",
    concept: "3진 탐색, 후보 제거, 정보량과 효율, 조건에 따른 경우 나눔.",
    think: "무게가 가벼운지 무거운지 '미리 안다면' 9개를 몇 번에 찾을 수 있을까요?",
  },
  learningGoals: ["3등분 전략(3진 탐색)", "저울 결과로 후보·방향 좁히기", "조건(방향)이 횟수에 미치는 영향"],
  curriculumTags: ["상태 표현", "알고리즘 설계", "선택 구조", "효율성 비교"],
  reflectionQuestions: ["방향을 모르면 왜 저울질이 한 번 더 필요할까요?"],
  answerSource: "book-and-verified",
  verificationMethod: "교재의 3회 저울 절차 재현 + 방향 미상 시 (3ᵏ−3)/2 한계 확인",
  verificationEvidence: "방향 미상 9개는 최소 3회(교재도 3회). (3²−3)/2=3<9≤(3³−3)/2=12. 예시 결과=6번.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["6번(무거움) / 방향 미상 9개 최소 3회"], optimal: "3회(방향 모름) · 방향 알면 2회",
    commonWrong: ["방향을 모르는데 2회로 단정", "2개씩 비교로 횟수 증가"], wrongWhy: "'방향 미상'과 '방향 기지'를 혼동.",
    questions: ["한 번의 저울질로 얻는 정보는 몇 가지인가?", "방향을 알면/모르면 횟수가 어떻게 달라지나?"],
    intro: "겉보기 같은 동전 이야기로 도입. 방향을 모른다는 점을 강조.",
    group: "모둠이 방향 미상 결정 트리를 그려 3회 필요함을 확인.",
    tune: "기초: '가볍다'고 알려주고 2회 도전(B-06). 도전: 12개 방향 미상 3회(5-21).",
    programming: "결정 트리로 (3ᵏ−3)/2 한계를 계산.",
    extension: ["12개 방향 미상 3회", "방향 알 때와 비교표 만들기"],
    eval: "방향 조건이 최소 횟수에 미치는 영향을 설명했는지 평가.", minutes: 6,
  },
});

PROBLEMS.push({
  id: "B-06", sourceProblem: "5-19", sourcePage: 96, world: "algorithm",
  title: "위조 동전 (가벼움)", engine: "balance", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "여러 동전 가운데 위조 동전이 하나 있고, 위조 동전은 정상보다 '조금 가볍다'. 양팔 저울로 위조 동전을 찾아라. 동전 수에 따라 몇 번이면 되는지, 가장 효율적인 방법은 무엇인지 생각하라.",
  studentFriendlyText:
    "위조 동전은 정상보다 '가벼워요'. 저울로 가벼운 동전을 찾아요!\n가벼운 게 확실하니, 저울이 '올라간 쪽'에 위조가 있어요. 최소 횟수로 찾아봐요(9개).",
  conditions: ["위조 동전은 더 가벼움(방향 알려짐)", "동전 9개", "가벼운 묶음/동전이 저울에서 위로 올라감"],
  irrelevantInformation: [],
  correctAnswers: ["5"], equivalentAnswers: ["5번 동전"],
  config: {
    kind: "balance", n: 9, oddIndex: 5, heavier: false, unknownDir: false,
    maxWeighings: 2, optimalWeighings: 2,
  },
  hint1Observation: "가벼운 게 확실해요. 저울에서 '올라가는 쪽'이 무엇을 뜻할까요?",
  hint2KeyCondition: "올라간 쪽 묶음에 위조(가벼운) 동전이 있어요. 3개씩 나눠요.",
  hint3NextAction: "두 묶음을 재서 올라간 쪽(또는 평형이면 안 올린 묶음)으로 좁히고, 그 안에서 2개를 다시 비교.",
  guidedSolution: [
    "9개를 3개씩 세 묶음.",
    "1차: 두 묶음 비교 → 올라간 묶음(가벼움)에 위조. 평형이면 남은 묶음.",
    "2차: 그 묶음의 2개 비교 → 올라간 쪽이 위조. 평형이면 남은 하나.",
    "→ 2번이면 특정. (이 스테이지 정답=5번, 가벼움)",
  ],
  fullExplanation: {
    answer: "위조 = 5번 (가벼움)", key: "방향(가벼움)을 알면 '올라간 쪽'만 쫓으면 됨.",
    abstraction: "후보 집합을 저울 결과(올라감=가벼운 쪽 포함)로 1/3씩 축소.",
    steps: ["3등분", "올라간(또는 평형→나머지) 묶음 선택", "그 안에서 다시 비교"],
    why: ["방향이 정해져 있어 판정이 단순해지고, 3등분으로 최소 횟수가 돼요."],
    verify: "올라간 쪽 = 가벼운 위조 포함. 두 번의 3등분으로 9→3→1.",
    mistakes: ["무거운 쪽을 쫓기", "평형일 때 나머지 묶음을 잊기"],
    failReason: "방향을 반대로 해석하면 정상 동전을 위조로 지목해요.",
    better: "한 번에 최대한 많이(3등분) 나누는 것이 최소 횟수의 핵심.",
    other: "N개면 최소 ⌈log₃N⌉번. (3개=1번, 9개=2번, 27개=3번)",
    concept: "선택 구조(조건 분기), 3진 탐색, 효율성.",
    think: "만약 무거운지 가벼운지 모른다면 왜 더 어려울까요?",
  },
  learningGoals: ["방향을 이용한 판정", "최소 횟수 ⌈log₃N⌉"],
  curriculumTags: ["선택 구조", "알고리즘 설계", "효율성 비교"],
  reflectionQuestions: ["방향 정보가 있어서 무엇이 쉬워졌나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "결정 트리로 2회 내 특정 확인(coinSolver, 가벼움 방향)",
  verificationEvidence: "9개·가벼움은 2회로 항상 특정. ⌈log₃9⌉=2.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["이 스테이지=5번 / 일반 9개=2회"], optimal: "2회(⌈log₃9⌉)",
    commonWrong: ["무거운 쪽 지목", "4회 이상(2개씩)"], wrongWhy: "방향 해석 오류, 비효율 분할.",
    questions: ["N개일 때 필요한 최소 횟수는?", "방향 정보의 가치는?"],
    intro: "'가벼운 위조'로 방향을 강조.",
    group: "모둠이 N을 바꿔가며 최소 횟수 표 만들기.",
    tune: "기초: 3개. 도전: 방향 모르는 12개.",
    programming: "재귀로 ⌈log₃N⌉ 검증 코드.",
    extension: ["방향 모름(5-20)", "12개 3회 전략(5-21)"],
    eval: "방향을 활용하고 최소 횟수를 논증했는지 평가.", minutes: 7,
  },
});

PROBLEMS.push({
  id: "B-07", sourceProblem: "5-23", sourcePage: 98, world: "algorithm",
  title: "하노이 타워", engine: "hanoi", difficulty: "normal", estimatedMinutes: 8,
  originalProblemText:
    "A,B,C 세 기둥에 원반이 A에 꽂혀 있다. 한 번에 하나의 원반만 옮길 수 있고, 큰 원반을 작은 원반 위에 놓을 수 없다. A의 원반을 모두 C로 옮기려면 최소 몇 번이면 되는가? 원반 2·3·4·5개에 대해 풀어보라.",
  studentFriendlyText:
    "원반을 A기둥에서 C기둥으로 모두 옮겨요! 규칙: 한 번에 하나, 큰 원반은 작은 원반 위에 못 놓아요.\n원반 개수를 바꿔가며 '최소 이동 횟수'를 찾아보세요.",
  conditions: ["한 번에 원반 1개", "큰 원반을 작은 원반 위에 놓을 수 없음", "A→C로 전부 이동"],
  irrelevantInformation: ["원반의 색은 무관"],
  correctAnswers: ["2개:3 / 3개:7 / 4개:15 / 5개:31 (2ⁿ−1)"], equivalentAnswers: ["2^n-1"],
  config: {
    kind: "hanoi", modes: [2, 3, 4, 5], defaultDisks: 3,
    minMoves: { 2: 3, 3: 7, 4: 15, 5: 31 },
  },
  hint1Observation: "원반 2개는 몇 번? 3개는? 개수와 횟수 사이의 규칙을 찾아보세요.",
  hint2KeyCondition: "n개를 옮기려면 'n−1개를 옮기고 → 가장 큰 것 1번 → 다시 n−1개'예요.",
  hint3NextAction: "그래서 f(n) = 2·f(n−1) + 1 이라는 규칙이 생겨요. f(1)부터 차근차근 늘려가며 직접 세어 보세요.",
  guidedSolution: [
    "n−1개를 보조 기둥으로 옮긴다(f(n−1)번).", "가장 큰 원반을 C로 옮긴다(1번).",
    "n−1개를 C로 옮긴다(f(n−1)번).", "합치면 f(n)=2·f(n−1)+1 → 2ⁿ−1. 2→3, 3→7, 4→15, 5→31.",
  ],
  fullExplanation: {
    answer: "최소 이동 = 2ⁿ−1 (2개=3, 3개=7, 4개=15, 5개=31)",
    key: "n의 문제를 n−1의 문제 두 번 + 1로 쪼개는 것(재귀/분할).",
    abstraction: "'n개 옮기기'를 더 작은 'n−1개 옮기기'로 나누는 반복 규칙으로 추상화.",
    steps: ["n−1개 보조로", "큰 것 1개 목표로", "n−1개 목표로", "f(n)=2f(n−1)+1"],
    why: ["큰 원반을 옮기려면 그 위 전부를 비워야 하므로 자연히 재귀가 나와요."],
    verify: "f(1)=1,f(2)=3,f(3)=7,f(4)=15,f(5)=31. 2ⁿ−1과 일치.",
    mistakes: ["규칙 위반(큰 원반을 작은 위에)", "불필요한 왕복으로 횟수 늘리기"],
    failReason: "부분 구조를 못 보면 중간에 헤매 이동이 늘어나요.",
    better: "재귀 규칙을 알면 항상 최소 2ⁿ−1로 옮길 수 있어요.",
    other: "홀짝 규칙(가장 작은 원반을 일정 방향으로)으로도 최소 이동 가능.",
    concept: "재귀, 분할 정복, 반복 규칙, 지수 증가.",
    think: "원반이 10개면 몇 번일까요? 하루에 다 옮길 수 있을까요?",
  },
  learningGoals: ["재귀적 분해", "규칙 일반화(2ⁿ−1)"],
  curriculumTags: ["문제 분해", "패턴과 일반화", "알고리즘 설계", "반복 구조"],
  reflectionQuestions: ["큰 문제를 어떤 작은 문제로 나눴나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "재귀 시뮬레이션으로 최소 이동 수 확인(hanoiSolver)",
  verificationEvidence: "규칙 위반 없이 2ⁿ−1회로 완료됨을 시뮬레이션으로 확인.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["2ⁿ−1 (경로는 유일한 최소)"], optimal: "2ⁿ−1",
    commonWrong: ["규칙 위반", "왕복 과다"], wrongWhy: "부분 구조 미인식.",
    questions: ["n을 어떤 더 작은 문제로 나눌 수 있나?"],
    intro: "전설(브라흐마 탑) 이야기로 흥미 유발.",
    group: "모둠이 2→3→4개 횟수를 재고 규칙 추측.",
    tune: "기초: 2·3개. 도전: 5개 최소로.",
    programming: "재귀 함수 hanoi(n,a,b,c)로 이동 출력.",
    extension: ["원반 n개 공식 증명", "이동 명령을 카드로 변환"],
    eval: "재귀 규칙을 찾고 규칙을 지키며 최소로 풀었는지 평가.", minutes: 8,
  },
});

PROBLEMS.push({
  id: "B-08", sourceProblem: "5-28", sourcePage: 103, world: "algorithm",
  title: "농부의 강 건너기", engine: "river", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "농부가 늑대·염소·배추를 데리고 강을 건너야 한다. 배에는 농부와 '다른 한 가지'만 탈 수 있다. 농부가 없을 때 늑대와 염소가 함께 있으면 염소가 잡아먹히고, 염소와 배추가 함께 있으면 배추가 먹힌다. 강을 몇 번 건너면 될까?",
  studentFriendlyText:
    "농부가 늑대·염소·배추를 강 건너로 옮겨요! 배에는 농부와 하나만 탈 수 있어요.\n농부가 자리를 비우면 '늑대+염소' 또는 '염소+배추'가 함께 있으면 안 돼요. 최소 횟수로 모두 건너요!",
  conditions: ["배: 농부 + 최대 1개", "농부 없이 늑대·염소 함께 금지", "농부 없이 염소·배추 함께 금지"],
  irrelevantInformation: ["강의 폭·날씨는 무관"],
  correctAnswers: ["7"], equivalentAnswers: ["7번"],
  config: {
    kind: "river",
    items: [ { id: "wolf", name: "늑대", emoji: "🐺" }, { id: "goat", name: "염소", emoji: "🐐" }, { id: "cabbage", name: "배추", emoji: "🥬" } ],
    farmer: { name: "농부", emoji: "🧑\u200d🌾" },
    // 위험 조합: 농부가 없는 쪽에 이 쌍이 함께 있으면 실패
    conflicts: [ ["wolf", "goat"], ["goat", "cabbage"] ],
    boatCapacity: 1, minCrossings: 7,
  },
  hint1Observation: "무엇이 가장 '위험한 가운데'에 있나요? 늑대도 배추도 위협하는 대상은?",
  hint2KeyCondition: "염소가 핵심! 염소를 먼저 건너보내면 늑대와 배추는 남아도 안전해요.",
  hint3NextAction: "염소를 옮긴 뒤, 늑대(또는 배추)를 옮기고 '염소를 다시 데려오는' 되돌리기가 열쇠예요.",
  guidedSolution: [
    "① 염소를 건너편으로.", "② 농부만 돌아옴.", "③ 늑대를 건너편으로.",
    "④ 염소를 다시 데리고 돌아옴.", "⑤ 배추를 건너편으로.", "⑥ 농부만 돌아옴.", "⑦ 염소를 건너편으로. → 완료(7번)",
  ],
  fullExplanation: {
    answer: "최소 7번 건너기",
    key: "염소를 '되돌리는' 수(4번째)를 두려워하지 않는 것.",
    abstraction: "강 양쪽의 구성을 '상태'로 보고, 안전한 상태만 지나며 이동(상태 그래프).",
    steps: ["염소 먼저", "늑대(또는 배추) 옮기고 염소 회수", "나머지 옮기고 마지막에 염소"],
    why: ["염소가 두 위험의 공통 원인이라, 염소를 통제하면 문제가 풀려요."],
    verify: "각 단계에서 금지 조합이 남지 않음을 확인 → 7번에 전부 안전 이동.",
    mistakes: ["염소를 되돌리지 않으려 함", "늑대·배추 순서만 바꾸면 된다고 생각"],
    failReason: "되돌리기를 피하면 어떤 순서로도 금지 조합이 생겨요.",
    better: "BFS로 최단 = 7번임을 확인. 늑대·배추는 순서를 바꿔도 7번(대칭 해).",
    other: "③에서 배추를 먼저 옮겨도 대칭으로 7번.",
    concept: "상태 표현, 상태 그래프, 최단 경로, 되돌리기 전략.",
    think: "왜 염소가 문제의 '핵심 요소'일까요?",
  },
  learningGoals: ["안전 상태 판정", "되돌리기를 포함한 계획", "최소 횟수"],
  curriculumTags: ["상태 표현", "선택 구조", "알고리즘 설계", "오류 수정"],
  reflectionQuestions: ["염소를 되돌리는 수가 왜 필요했나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "BFS 상태 탐색으로 최단 7회 확인(riverCrossingSolver)",
  verificationEvidence: "안전 상태만으로 시작→목표 최단 경로 = 7회. 대칭 해 2가지.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["7회(늑대/배추 순서 바꾼 대칭 해 포함)"], optimal: "7회",
    commonWrong: ["6회로 착각", "되돌리기 없이 시도"], wrongWhy: "되돌리기 회피.",
    questions: ["금지 조합의 공통 원인은?", "왜 되돌리기가 필요할까?"],
    intro: "옛이야기로 도입, 인형/카드로 시연.",
    group: "모둠이 상태표를 만들며 안전/위험을 표시.",
    tune: "기초: 늑대·염소만. 도전: 선교사와 식인종(5-25).",
    programming: "상태를 비트로 표현하고 BFS로 최단 경로 탐색.",
    extension: ["선교사·식인종", "원숭이 강 건너기(5-39)"],
    eval: "안전 상태 판정과 되돌리기 전략을 이해했는지 평가.", minutes: 7,
  },
});

PROBLEMS.push({
  id: "B-09", sourceProblem: "5-44", sourcePage: 109, world: "algorithm",
  title: "최대의 길", engine: "maxpath", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "왼쪽 맨 아래에서 출발하여 위쪽 또는 오른쪽으로만 이동해 오른쪽 맨 위로 간다. 지나는 칸의 숫자 합을 최대로 하는 길의 숫자들을 적어라.",
  studentFriendlyText:
    "왼쪽 아래에서 출발해 '위' 또는 '오른쪽'으로만 움직여 오른쪽 위 칸까지 가요.\n지나는 숫자의 합이 가장 크도록 길을 만들어요! (되돌아가기 없음)",
  conditions: ["이동은 위 또는 오른쪽만", "시작=왼쪽 아래, 끝=오른쪽 위", "지난 칸 숫자의 합을 최대로"],
  irrelevantInformation: ["칸의 색은 무관"],
  correctAnswers: ["31"], equivalentAnswers: ["최대 합 31"],
  config: {
    kind: "maxpath",
    grid: [ [3,8,1,1], [2,9,4,7], [5,2,6,3], [3,4,2,8] ], // 위→아래 행
    start: [3,0], end: [0,3], maxSum: 31,
  },
  hint1Observation: "매 칸에서 '위로 갈지 오른쪽으로 갈지'만 고르면 돼요. 큰 수 쪽으로 가고 싶겠죠?",
  hint2KeyCondition: "그런데 눈앞의 큰 수만 쫓으면 손해일 수 있어요. '끝에서 거꾸로' 각 칸까지의 최대 합을 적어보면 정확해요.",
  hint3NextAction: "각 칸의 최대 합 = 그 칸 값 + (아래칸·왼칸 중 큰 값). 이렇게 채우면 오른쪽 위 칸이 정답 합이에요.",
  guidedSolution: [
    "각 칸까지 오는 '최대 합'을 아래·왼쪽부터 채워요(동적 계획법).",
    "칸 최대합 = 값 + max(아래에서 온 값, 왼쪽에서 온 값).",
    "오른쪽 위 칸의 최대합 = 31.",
    "거꾸로 따라가면 예: 3→5→2→9→4→7→1 (합 31).",
  ],
  fullExplanation: {
    answer: "최대 합 = 31",
    key: "'지금까지의 최대 합'을 칸마다 저장해 재사용(중복 계산 제거).",
    abstraction: "격자를 표로 보고, 각 칸에 '거기까지 최대 합'을 채우는 문제로 단순화.",
    steps: ["시작 칸부터 최대합 표 채우기", "각 칸=값+max(아래,왼쪽)", "끝 칸 값=31", "역추적으로 경로 확인"],
    why: ["같은 칸을 여러 번 계산하지 않아 빠르고 정확해요(효율)."],
    verify: "동적 계획법 표의 오른쪽 위 = 31. 예시 경로 합도 31로 일치.",
    mistakes: ["매번 큰 수만 따라가는 '욕심쟁이'(최적 아님)", "왼/아래 대신 대각선 이동"],
    failReason: "눈앞의 큰 수만 고르면 뒤에서 더 큰 합을 놓칠 수 있어요.",
    better: "모든 경로를 하나씩 더하면 느려요. 표에 최대합을 저장하면 훨씬 빨라요.",
    other: "정답 합이 같은 여러 경로가 있을 수 있어요(합 31이면 모두 정답).",
    concept: "상태 표현, 동적 계획법, 최적 부분 구조, 효율 비교.",
    think: "'욕심쟁이'로 갔을 때와 정답을 비교하면 어떤 차이가 있나요?",
  },
  learningGoals: ["동적 계획법(표 채우기)", "최적 경로 탐색", "욕심쟁이와 비교"],
  curriculumTags: ["상태 표현", "알고리즘 설계", "반복 구조", "효율성 비교"],
  reflectionQuestions: ["왜 '끝에서부터' 또는 '표로' 생각하면 정확할까요?"],
  answerSource: "derived",
  verificationMethod: "동적 계획법 + 완전 탐색 대조(maxPathSolver)",
  verificationEvidence: "DP와 모든 경로 완전 탐색 모두 최대 합 31로 일치.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["최대 합 31 (같은 합의 경로 여러 개)"], optimal: "합 31",
    commonWrong: ["욕심쟁이 경로(합<31)", "대각선 이동"], wrongWhy: "지역 최적에 빠짐.",
    questions: ["욕심쟁이는 왜 실패할 수 있나?", "표에 무엇을 저장했나?"],
    intro: "숫자 삼각형(최대 합) 이야기로 도입.",
    group: "모둠이 DP 표를 함께 채우기.",
    tune: "기초: 3×3. 도전: 최소 합·경로 개수 세기.",
    programming: "2차원 배열 DP로 최대 합을 구하는 코드.",
    extension: ["최소 합 경로", "경로 개수 세기"],
    eval: "표(DP)로 최적을 구하고 욕심쟁이와 비교했는지 평가.", minutes: 7,
    note: "원본은 격자 그림. 시작 3·끝 1 조건을 유지해 4×4 격자로 재구성하고 솔버로 검증.",
  },
});

// ================= 월드 3 · 추상화 ＋ 알고리즘 =================

PROBLEMS.push({
  id: "C-01", sourceProblem: "4-1", sourcePage: 48, world: "both",
  title: "동전의 수", engine: "iterate", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "나는 100원짜리와 50원짜리 동전을 합해 15개 가지고 있다. 친구는 100원짜리를 나의 반, 50원짜리를 나의 3배 가지고 있는데, 돈의 합계는 같다. 나의 100원짜리 동전은 몇 개인가?",
  studentFriendlyText:
    "나는 100원·50원 동전을 합쳐 15개 가지고 있어요. 친구의 100원은 내 절반, 50원은 내 3배인데\n둘의 돈 합계가 같대요. 표를 채우며 규칙을 찾아, 나의 100원 동전 개수를 구해요!",
  conditions: ["나: 100원+50원 = 15개", "친구 100원 = 나의 100원 ÷ 2 (그래서 나의 100원은 짝수)", "친구 50원 = 나의 50원 × 3", "두 사람 돈 합계 같음"],
  irrelevantInformation: [],
  correctAnswers: ["10"], equivalentAnswers: ["10개"],
  config: {
    kind: "iterate", mode: "search",
    varLabel: "나의 100원 동전 수 N",
    candidates: [2, 4, 6, 8, 10, 12, 14],
    columns: ["N(내 100원)", "내 50원(15−N)", "내 합계", "친구 100원(N÷2)", "친구 50원(3×(15−N))", "친구 합계"],
    row: (N) => [N, 15 - N, 100 * N + 50 * (15 - N), N / 2, 3 * (15 - N), 100 * (N / 2) + 50 * 3 * (15 - N)],
    matchCol: [2, 5], // '내 합계' == '친구 합계'
    answer: 10,
  },
  hint1Observation: "'친구 100원 = 내 것의 반'이라면, 내 100원 개수는 홀수일까요 짝수일까요?",
  hint2KeyCondition: "반으로 나눠떨어져야 하니 내 100원은 '짝수'예요. 그래서 N=2,4,6…만 확인하면 돼요.",
  hint3NextAction: "표에서 '내 합계'와 '친구 합계'가 같아지는 N을 찾으세요. N이 2 커질 때 두 합계가 어떻게 변하는지 보세요.",
  guidedSolution: [
    "N을 짝수만 넣어 표를 채워요(반복).",
    "내 합계 = 100N + 50(15−N), 친구 합계 = 50N + 150(15−N).",
    "N이 2 커지면 내 합계는 +100, 친구 합계는 −200(규칙).",
    "두 합계가 같아지는 N = 10. (내 합계=친구 합계=1250원)",
  ],
  fullExplanation: {
    answer: "나의 100원짜리 동전 = 10개",
    key: "'반으로 나눠짐'에서 N이 짝수라는 숨은 조건을 뽑아 후보를 절반으로 줄이는 것.",
    abstraction: "상황을 변수 N과 두 개의 합계 식으로 바꾸고, N을 반복(loop)으로 검사.",
    steps: ["N 짝수만 후보", "표 채우기(반복)", "두 합계가 같은 N 찾기", "N=10"],
    why: ["표로 규칙(내 +100, 친구 −200)을 보면 방정식 없이도 답이 보여요."],
    verify: "N=10: 내 100원 10,50원 5 → 1000+250=1250. 친구 100원 5,50원 15 → 500+750=1250 ✓.",
    mistakes: ["N을 홀수까지 다 넣기", "친구 50원을 '3배'가 아니라 '÷3'으로 계산"],
    failReason: "숨은 조건(짝수)을 못 찾으면 검사할 경우가 두 배로 늘어요.",
    better: "방정식 100N+50(15−N)=50N+150(15−N) → N=10. 표/규칙으로도 동일.",
    other: "‘두 합계 차이’를 N의 함수로 보고 0이 되는 지점을 찾아도 됨.",
    concept: "변수·조건 추출, 반복 구조, 선택(조건) 구조, 표 모델.",
    think: "N이 2 커질 때 두 합계가 각각 얼마씩 변했나요? 그 규칙으로 답을 예측할 수 있나요?",
  },
  learningGoals: ["변수·조건 추출", "반복으로 후보 검사", "숨은 조건 활용"],
  curriculumTags: ["핵심 정보 추출", "추상화", "반복 구조", "선택 구조", "프로그래밍으로 표현하기"],
  reflectionQuestions: ["표를 만든 것이 왜 도움이 되었나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "N=0..15 전수 검사 + 방정식 풀이(solver)",
  verificationEvidence: "두 합계가 같아지는 N은 10뿐(짝수 조건 포함).",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["10"], optimal: "짝수만 검사 → N=10",
    commonWrong: ["6, 8 (합계 비교 오류)", "친구 50원 계산 실수"], wrongWhy: "숨은 조건·식 오류.",
    questions: ["'반'이라는 말에서 무엇을 알 수 있나?", "N 증가에 따른 합계 규칙은?"],
    intro: "실제 동전으로 상황을 재현.",
    group: "모둠이 표를 나눠 채우고 규칙을 발표.",
    tune: "기초: 표 절반 제공. 도전: 방정식으로 일반화.",
    programming: "for(N=2;N<=14;N+=2) if(myTotal==frTotal) print(N) 작성.",
    extension: ["동전 종류·개수 바꿔 일반화", "그래프로 두 합계 교차점 보기"],
    eval: "변수·조건을 뽑아 반복 검사를 설계했는지 평가.", minutes: 7,
  },
});

PROBLEMS.push({
  id: "C-02", sourceProblem: "4-16", sourcePage: 55, world: "both",
  title: "크리스마스 선물", engine: "iterate", difficulty: "normal", estimatedMinutes: 6,
  originalProblemText:
    "'열이틀의 크리스마스' 노래처럼 첫째 날 선물 1개, 둘째 날 (1+2)개, 셋째 날 (1+2+3)개 … 열두째 날까지 받는다. 열두째 날까지 받은 선물은 모두 몇 개인가? 규칙을 찾고 순서도로 표현하라.",
  studentFriendlyText:
    "날마다 받는 선물이 늘어나요. 하루 선물 = 어제 하루 선물 + 오늘 날짜!\n표를 하루씩 채우며 12일까지의 '총 선물 수'를 구해요. 마구 더하지 말고 규칙을 이용해요.",
  conditions: ["오늘 하루 선물 = 어제 하루 선물 + 오늘 날짜", "오늘까지 총합 = 어제 총합 + 오늘 하루 선물", "12일까지"],
  irrelevantInformation: ["노래 가사의 구체 선물 종류는 무관"],
  correctAnswers: ["364"], equivalentAnswers: ["364개"],
  config: {
    kind: "iterate", mode: "accumulate",
    days: 12, initDaily: 1, initTotal: 1,
    columns: ["날짜", "하루 선물 수", "오늘까지 총합"],
    answer: 364,
  },
  hint1Observation: "1일 총합 1, 2일에는 하루 선물이 몇 개로 늘까요?(1+2)",
  hint2KeyCondition: "하루 선물 = 어제 하루 선물 + 오늘 날짜. 총합 = 어제 총합 + 오늘 하루 선물.",
  hint3NextAction: "이 두 규칙으로 표를 12일까지 채우면 총합이 나와요. 매번 다 더하지 않아도 돼요!",
  guidedSolution: [
    "1일: 하루1, 총합1.", "2일: 하루=1+2=3, 총합=1+3=4.", "3일: 하루=3+3=6, 총합=4+6=10.",
    "… 규칙대로 12일까지 반복.", "12일 총합 = 364.",
  ],
  fullExplanation: {
    answer: "364개",
    key: "매일 처음부터 다시 더하지 않고, '어제 값'을 재사용하는 것(누적).",
    abstraction: "선물 수를 두 변수(하루 선물, 총합)로 두고 반복 규칙으로 표현.",
    steps: ["하루 선물 = 어제 + 날짜", "총합 = 어제 총합 + 하루 선물", "12일까지 반복", "총합 364"],
    why: ["누적 규칙을 쓰면 더하기 횟수를 77번 → 20번으로 줄일 수 있어요(효율)."],
    verify: "삼각수 합 1+3+6+…+78 = 364 (사면체수 12·13·14/6). 표 결과와 일치.",
    mistakes: ["'하루 선물'과 '총합'을 헷갈리기", "매일 1부터 다시 더해 계산량 폭증"],
    failReason: "규칙 없이 매번 전부 더하면 계산이 많고 실수하기 쉬워요.",
    better: "누적 변수 2개만 쓰면 반복 한 번에 갱신 → 훨씬 빠름.",
    other: "공식 n(n+1)(n+2)/6로 한 번에도 계산 가능.",
    concept: "반복 구조, 누적 변수, 순서도, 효율(계산 횟수) 비교.",
    think: "20일까지라면 총합은? 규칙을 그대로 늘려 계산해 보세요.",
  },
  learningGoals: ["누적(반복) 알고리즘 설계", "계산 횟수 줄이기"],
  curriculumTags: ["추상화", "모델링", "반복 구조", "알고리즘 실행", "효율성 비교", "프로그래밍으로 표현하기"],
  reflectionQuestions: ["'어제 값'을 재사용한 것이 왜 이득인가요?"],
  answerSource: "book-and-verified",
  verificationMethod: "반복 시뮬레이션 + 공식 n(n+1)(n+2)/6 대조",
  verificationEvidence: "시뮬레이션 총합 364 = 12·13·14/6 = 364.",
  teacher: {
    origDifficulty: "레벨 2", allAnswers: ["364"], optimal: "누적 반복 20회 더하기",
    commonWrong: ["78(마지막 하루만)", "매일 재계산 실수"], wrongWhy: "하루/총합 혼동.",
    questions: ["더하기 횟수를 어떻게 줄였나?", "순서도로 어떻게 표현할까?"],
    intro: "노래를 함께 부르며 규칙 찾기.",
    group: "모둠이 표를 이어 채우며 누적 관찰.",
    tune: "기초: 6일까지. 도전: 공식 유도.",
    programming: "for 반복 + 누적 변수로 총합 계산 코드.",
    extension: ["n일 일반식", "순서도 그리기"],
    eval: "누적 규칙으로 계산 횟수를 줄였는지 평가.", minutes: 6,
  },
});

PROBLEMS.push({
  id: "C-03", sourceProblem: "4-75", sourcePage: 80, world: "both",
  title: "그래프 유추 · 쾨니히스베르크 다리", engine: "graph", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "쾨니히스베르크에 강과 두 개의 섬, 그리고 7개의 다리가 있다. 7개의 다리를 한 번씩만 건너 처음 자리로 돌아오는 길을 찾아라.",
  studentFriendlyText:
    "땅을 '점', 다리를 '선'으로 바꿔 그래프로 만들어요! 그러면 다리 건너기가 '한붓그리기'가 돼요.\n각 점에 연결된 선의 개수(차수)를 세어, 한 번씩 다 건너 제자리로 올 수 있는지 판단해요.",
  conditions: ["다리(선)를 한 번씩만 건넌다", "처음 위치로 돌아온다(닫힌 경로)", "땅=점(꼭짓점), 다리=선(변)으로 추상화"],
  irrelevantInformation: ["다리의 길이·강 폭은 무관"],
  correctAnswers: ["불가능"], equivalentAnswers: ["불가능(모든 꼭짓점 차수가 홀수)"],
  config: {
    kind: "graph", mode: "analyze",
    nodes: [ { id: "A", name: "북쪽 땅", x: 260, y: 40 }, { id: "B", name: "남쪽 땅", x: 260, y: 300 },
             { id: "C", name: "큰 섬", x: 120, y: 170 }, { id: "D", name: "작은 섬", x: 400, y: 170 } ],
    edges: [ ["A","C"], ["A","C"], ["B","C"], ["B","C"], ["A","D"], ["B","D"], ["C","D"] ],
    question: "7개의 다리를 한 번씩 모두 건너 '제자리로 돌아오는' 길이 있을까요?",
    answer: "impossible", // 닫힌 한붓그리기(오일러 회로) 가능 여부
    degrees: { A: 3, B: 3, C: 5, D: 3 },
  },
  hint1Observation: "각 점(땅)에 연결된 선(다리)이 몇 개인지 세어 보세요.",
  hint2KeyCondition: "한붓그리기로 '제자리로 돌아오려면' 모든 점의 선 개수(차수)가 '짝수'여야 해요.",
  hint3NextAction: "차수가 홀수인 점이 몇 개인지 세어, '모든 차수가 짝수여야 한다'는 조건과 비교해 보세요.",
  guidedSolution: [
    "땅을 점, 다리를 선으로 바꿔 그래프로 그린다.",
    "차수: 북3, 남3, 큰섬5, 작은섬3 — 모두 홀수.",
    "닫힌 한붓그리기는 '모든 차수 짝수'가 필요.",
    "홀수 점이 4개 → 열린 한붓그리기(홀수 점 2개)도 불가능. 따라서 불가능.",
  ],
  fullExplanation: {
    answer: "불가능 (오일러가 증명)",
    key: "'다리를 한 번씩'은 각 점을 '들어온 만큼 나가야' 하므로 차수가 짝수여야 한다는 것.",
    abstraction: "땅→점, 다리→선(그래프). 필요한 정보는 '연결 관계'뿐(위치·길이 제거).",
    steps: ["그래프로 변환", "각 점 차수 세기", "홀수 차수 점 개수 확인", "0개면 회로/2개면 경로/그 외 불가능"],
    why: ["점에 드나들 때마다 선 2개를 쓰므로, 시작·끝이 같으려면 모든 차수가 짝수여야 해요."],
    verify: "차수(3,3,5,3) 모두 홀수 → 홀수 점 4개 → 오일러 회로·경로 모두 불가.",
    mistakes: ["실제 지도의 모양에 집착", "차수를 잘못 세기(평행한 다리 놓침)"],
    failReason: "위치·거리 같은 불필요한 정보에 매달리면 핵심(연결·차수)을 놓쳐요.",
    better: "그래프로 바꾸면 5040가지 경로를 다 해보지 않고 차수만으로 즉시 판정.",
    other: "시작·끝을 달리 해도(열린 경로) 홀수 점이 4개라 불가능.",
    concept: "그래프(점·선), 차수, 오일러 회로/경로, 추상화(불필요 정보 제거).",
    think: "다리 하나를 더 놓아 홀수 점을 2개로 만들면 한붓그리기가 될까요?",
  },
  learningGoals: ["실물→그래프 추상화", "차수로 한붓그리기 판정"],
  curriculumTags: ["추상화", "모델링", "상태 표현", "패턴과 일반화"],
  reflectionQuestions: ["어떤 정보를 버리고 어떤 정보만 남겼나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "차수 계산 + 오일러 정리(홀수 차수 점 개수) 확인(graphTrailSolver)",
  verificationEvidence: "차수 합 14=2×7. 홀수 차수 점 4개 → 회로·경로 모두 불가능.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["불가능"], optimal: "차수로 즉시 판정",
    commonWrong: ["가능하다고 착각(경로를 계속 시도)"], wrongWhy: "그래프 추상화·차수 개념 부재.",
    questions: ["왜 차수가 짝수여야 하나?", "무엇을 버리고 무엇을 남겼나?"],
    intro: "지도 그림을 점·선 그래프로 함께 바꿔 그리기.",
    group: "모둠이 차수를 세고 판정 규칙을 정리.",
    tune: "기초: 차수만 세기. 도전: 다리 추가로 가능하게 만들기.",
    programming: "인접 리스트로 차수를 세고 홀수 개수를 판정하는 코드.",
    extension: ["다리 추가/제거 실험", "우리 학교 지도로 그래프 만들기"],
    eval: "실물을 그래프로 추상화하고 차수로 판정했는지 평가.", minutes: 7,
  },
});

PROBLEMS.push({
  id: "C-04", sourceProblem: "4-77", sourcePage: 82, world: "both",
  title: "한붓그리기 (야자수)", engine: "graph", difficulty: "normal", estimatedMinutes: 7,
  originalProblemText:
    "종이에서 연필을 떼지 않고, 한 번 지나간 선을 다시 지나지 않으면서 그림을 그리고 싶다. 어떻게 그려야 하는지 순서대로 번호를 적어라.",
  studentFriendlyText:
    "연필을 떼지 않고 모든 선을 한 번씩만 지나 그림을 완성해요(한붓그리기)!\n먼저 차수가 홀수인 점을 찾아 거기서 출발하는 게 열쇠예요. 선을 순서대로 이어 보세요.",
  conditions: ["모든 선을 한 번씩만 지난다", "연필을 떼지 않는다(이어진 경로)", "홀수 차수 점은 0개 또는 2개여야 그릴 수 있음"],
  irrelevantInformation: ["선의 색·굵기는 무관"],
  correctAnswers: ["D 또는 E에서 시작하여 8개의 선을 모두 한 번씩"], equivalentAnswers: [],
  config: {
    kind: "graph", mode: "trail",
    nodes: [ { id: "A", name: "꼭대기", x: 260, y: 30 }, { id: "B", name: "왼위", x: 120, y: 130 },
             { id: "C", name: "오른위", x: 400, y: 130 }, { id: "D", name: "왼아래", x: 120, y: 300 },
             { id: "E", name: "오른아래", x: 400, y: 300 } ],
    edges: [ ["A","B"], ["A","C"], ["B","C"], ["B","D"], ["C","E"], ["D","E"], ["B","E"], ["C","D"] ],
    startNodes: ["D", "E"], // 홀수 차수 점
    totalEdges: 8,
    degrees: { A: 2, B: 4, C: 4, D: 3, E: 3 },
  },
  hint1Observation: "각 점의 선 개수(차수)를 세어, 홀수인 점을 찾아보세요.",
  hint2KeyCondition: "홀수 차수 점이 딱 2개예요(왼아래 D, 오른아래 E). 한붓그리기는 이 둘 중 하나에서 시작해요.",
  hint3NextAction: "차수가 홀수인 점에서 출발해, 아직 안 지난 선을 골라 계속 이어 보세요. 막히면 다시 그리기로 재시도!",
  guidedSolution: [
    "차수 확인: A2,B4,C4,D3,E3 → 홀수는 D,E(2개).",
    "한붓그리기 가능! D에서 출발.",
    "예: D→B→A→C→B→E→C→D→E (8개 선 모두 한 번씩).",
    "E에서 끝남(다른 홀수 점).",
  ],
  fullExplanation: {
    answer: "가능 — 홀수 차수 점(D 또는 E)에서 시작해 8개의 선을 모두 한 번씩",
    key: "홀수 차수 점이 정확히 2개면, 그 중 하나에서 시작해 다른 하나에서 끝난다.",
    abstraction: "그림을 점·선 그래프로 바꾸고, 차수의 홀짝으로 시작점을 정함.",
    steps: ["그래프로 변환", "차수 세기 → 홀수 점 2개", "홀수 점에서 출발", "안 지난 선 따라 8개 완주"],
    why: ["홀수 점에서 시작하지 않으면 도중에 반드시 막혀요(들어가면 못 나오는 점 발생)."],
    verify: "홀수 점 2개(D,E) → 오일러 경로 존재. 예시 순서가 8개 선을 모두 한 번씩 사용.",
    mistakes: ["짝수 점(A·B·C)에서 시작", "이미 지난 선을 또 지나기"],
    failReason: "시작점을 잘못 고르면 한 선이 남거나 갇혀요.",
    better: "차수를 먼저 세면 '가능 여부'와 '어디서 시작'을 바로 알 수 있어요.",
    other: "E에서 시작하는 대칭 경로도 정답. 순서는 여러 가지.",
    concept: "그래프, 차수, 오일러 경로, 알고리즘 실행·수정.",
    think: "만약 홀수 점이 0개라면 어디서 시작하고 어디서 끝날까요?",
  },
  learningGoals: ["그래프 추상화", "차수로 시작점 결정", "경로 실행·오류 수정"],
  curriculumTags: ["추상화", "모델링", "알고리즘 실행", "오류 수정"],
  reflectionQuestions: ["왜 홀수 차수 점에서 시작해야 했나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "오일러 경로 존재 판정 + 실제 경로 탐색(graphTrailSolver)",
  verificationEvidence: "홀수 차수 점 정확히 2개 → 경로 존재. 8개 변을 모두 사용하는 경로 확인.",
  teacher: {
    origDifficulty: "레벨 1", allAnswers: ["D 또는 E 시작, 순서는 여러 가지"], optimal: "홀수 점 시작",
    commonWrong: ["짝수 점 시작으로 막힘", "선 재사용"], wrongWhy: "차수 판정 미사용.",
    questions: ["시작점을 어떻게 정했나?", "그래프로 바꾸니 무엇이 쉬워졌나?"],
    intro: "봉투·별 그림 한붓그리기 놀이로 도입.",
    group: "모둠이 여러 도형의 차수를 세어 가능/불가능 분류.",
    tune: "기초: 더 적은 선의 도형. 도전: 시작·끝 지점 예측하기.",
    programming: "오일러 경로를 찾는 알고리즘(Hierholzer) 소개.",
    extension: ["여러 도형 분류", "우리 반 자리 그래프 한붓그리기"],
    eval: "차수로 시작점을 정하고 경로를 완주했는지 평가.", minutes: 7,
    note: "원본은 야자수 그림. 홀수 차수 점 2개를 갖는 '한붓그리기 가능' 그래프(봉투형)로 재구성.",
  },
});

PROBLEMS.push({
  id: "C-05", sourceProblem: "5-24", sourcePage: 100, world: "both",
  title: "다리 건너기", engine: "bridge", difficulty: "challenge", estimatedMinutes: 9,
  originalProblemText:
    "산악인 4명이 위험한 다리 앞에 있다. 다리는 한 번에 한 명 또는 두 명이 건널 수 있고, 손전등은 하나뿐이라 손전등이 있어야 건널 수 있다. 네 명의 건너는 시간은 1,2,5,10분이고, 두 명이 함께 건너면 느린 사람 속도로 건넌다. 네 명이 모두 건너는 최소 시간은? (19분은 답이 아니다)",
  studentFriendlyText:
    "4명(1·2·5·10분)이 손전등 하나로 다리를 건너요! 한 번에 최대 2명, 두 명이면 느린 사람 시간만큼 걸려요.\n손전등은 누군가 다시 가져와야 해요. 모두 건너는 '최소 시간'을 찾아요! (19분보다 빠른 방법이 있어요)",
  conditions: ["한 번에 1~2명", "손전등 1개(있어야 건넘, 누군가 되가져옴)", "두 명이면 느린 사람 시간", "시간 1,2,5,10분"],
  irrelevantInformation: ["산·계곡 배경은 무관"],
  correctAnswers: ["17"], equivalentAnswers: ["17분"],
  config: {
    kind: "bridge",
    people: [ { id: "a", name: "민준", emoji: "🏃", time: 1 }, { id: "b", name: "서연", emoji: "🚶", time: 2 },
              { id: "c", name: "삼촌", emoji: "🧔", time: 5 }, { id: "d", name: "할머니", emoji: "👵", time: 10 } ],
    boatMax: 2, minTime: 17, wrongCommon: 19,
  },
  hint1Observation: "가장 느린 두 사람(5분·10분)을 '언제' 건네야 손해가 적을까요?",
  hint2KeyCondition: "느린 두 명을 '함께' 건너보내면 10분 한 번으로 둘을 옮겨요. 대신 빠른 두 명이 손전등을 나른다.",
  hint3NextAction: "가장 느린 두 사람을 '함께' 건너보내고, 빠른 두 사람이 손전등을 나르는 역할을 하도록 순서를 짜 보세요.",
  guidedSolution: [
    "1·2 건너감(2분) → 1 돌아옴(1분). [누계 3]",
    "5·10 건너감(10분) → 2 돌아옴(2분). [누계 15]",
    "1·2 건너감(2분). [누계 17] ✅ 모두 건넘.",
    "핵심: 느린 두 명을 한 번에 묶어 보내고, 빠른 두 명이 손전등을 나른다.",
  ],
  fullExplanation: {
    answer: "최소 17분",
    key: "느린 두 사람(5,10)을 '같이' 건너게 해 10분을 한 번만 쓰는 것.",
    abstraction: "상태 = (이쪽 사람들, 저쪽 사람들, 손전등 위치). 이동은 상태 변화로 시간 누적.",
    steps: ["1·2 건너 →1 복귀(3)", "5·10 건너 →2 복귀(15)", "1·2 건너(17)"],
    why: ["가장 느린 둘을 따로 보내면 10+5가 각각 들어 손해. 함께 보내면 10 한 번."],
    verify: "완전 탐색(모든 이동 순서) 결과 최소 = 17분. 19분 방법(1이 매번 왕복)은 최적 아님.",
    mistakes: ["가장 빠른 1이 매번 왕복(→19분)", "느린 둘을 따로 보내기"],
    failReason: "‘빠른 사람이 셔틀’ 전략은 직관적이지만 느린 둘을 분리해 손해예요.",
    better: "느린 둘을 묶는 전략이 17분으로 최적. (직관적 19분보다 2분 절약)",
    other: "2가 첫 복귀 대신 1이 복귀하는 순서 차이는 있어도 최소는 17분.",
    concept: "상태 표현, 탐색, 효율(최소 시간), 반례로 직관 교정.",
    think: "왜 '가장 빠른 사람이 다 나른다'는 전략이 최적이 아닐까요?",
  },
  learningGoals: ["누적 시간 계산", "최소 시간 탐색", "직관 반례 이해"],
  curriculumTags: ["상태 표현", "알고리즘 설계", "효율성 비교", "오류 수정"],
  reflectionQuestions: ["느린 두 사람을 함께 보낸 이유는?"],
  answerSource: "book-and-verified",
  verificationMethod: "모든 이동 순서 완전 탐색으로 최소 시간 확인(bridgeSolver)",
  verificationEvidence: "완전 탐색 최소 = 17분. 19분은 비최적 경로.",
  teacher: {
    origDifficulty: "레벨 3", allAnswers: ["17분(복귀자 순서 차이의 대칭 해 존재)"], optimal: "17분",
    commonWrong: ["19분(1이 셔틀)"], wrongWhy: "느린 둘 분리.",
    questions: ["느린 둘을 어떻게 처리해야 하나?", "왜 19분은 최적이 아닌가?"],
    intro: "마이크로소프트 면접 문제 일화로 흥미 유발.",
    group: "모둠이 19분·17분 방법을 각각 시연·비교.",
    tune: "기초: 3명(1,2,5). 도전: 시간 값을 바꿔 일반 규칙 찾기.",
    programming: "상태 완전 탐색/DFS로 최소 시간 계산.",
    extension: ["5명으로 확장", "일반적 최적 전략 규칙 도출"],
    eval: "최소 시간 전략과 그 이유를 설명했는지 평가.", minutes: 9,
  },
});

PROBLEMS.push({
  id: "C-06", sourceProblem: "5-45", sourcePage: 109, world: "both",
  title: "30개의 열린 문", engine: "doors", difficulty: "challenge", estimatedMinutes: 8,
  originalProblemText:
    "30명이 30개의 문 앞을 지나간다. 첫째 사람은 모든 열린 문을 닫고, 둘째 사람은 2의 배수 문마다 열린 건 닫고 닫힌 건 열고, 셋째 사람은 3의 배수 문마다 … 이렇게 모두 지나간다. 30명이 지난 뒤 열려 있는 문은 몇 개인가?",
  studentFriendlyText:
    "문 30개가 모두 '열린 상태'로 시작해요. k번째 사람은 k의 배수 번호 문을 모두 '반대로' 바꿔요.\n30명이 다 지난 뒤 '열린 문'이 몇 개인지 직접 실행해 보고, 규칙도 찾아보세요!",
  conditions: ["문 30개, 처음 모두 열림", "k번째 사람은 k,2k,3k… 번 문을 토글(열림↔닫힘)", "1~30번째 사람까지"],
  irrelevantInformation: ["문의 색·크기는 무관"],
  correctAnswers: ["25"], equivalentAnswers: ["25개", "열린 문 25개(닫힌 문=제곱수 5개)"],
  config: {
    kind: "doors", n: 30, startOpen: true, answerOpen: 25,
    closed: [1, 4, 9, 16, 25], // 닫힌 문 = 제곱수
  },
  hint1Observation: "문 하나가 '몇 번' 바뀌는지 세어 보세요. 몇 번 사람이 그 문을 건드릴까요?",
  hint2KeyCondition: "d번 문은 'd의 약수' 개수만큼 토글돼요. 처음 열려 있으니 토글이 '짝수 번'이면 그대로 열림.",
  hint3NextAction: "문 하나가 바뀌는 횟수는 그 번호의 '약수 개수'와 같아요. 약수 개수가 홀수인지 짝수인지 따져 보세요.",
  guidedSolution: [
    "d번 문의 토글 횟수 = d의 약수 개수.",
    "처음 열림 → 토글이 짝수면 열림, 홀수면 닫힘.",
    "약수 개수가 홀수인 수 = 제곱수(1,4,9,16,25).",
    "그 5개만 닫힘 → 열린 문 = 30 − 5 = 25개.",
  ],
  fullExplanation: {
    answer: "열린 문 25개 (닫힌 문 = 제곱수 1,4,9,16,25 다섯 개)",
    key: "문 d의 상태를 바꾸는 사람은 'd의 약수'인 사람들뿐 → 토글 횟수 = 약수 개수.",
    abstraction: "각 문을 '토글 횟수의 홀짝'으로 추상화. 약수 개수의 홀짝만 보면 됨.",
    steps: ["문 d 토글 = 약수 개수", "처음 열림→짝수면 열림", "홀수(제곱수)만 닫힘", "30−5=25"],
    why: ["약수는 보통 쌍(예 12=1×12,2×6,3×4)이라 짝수인데, 제곱수만 √d가 짝을 못 이뤄 홀수예요."],
    verify: "직접 시뮬레이션(30명 토글) 결과 닫힌 문 = {1,4,9,16,25}, 열린 문 25개. 약수 성질과 일치.",
    mistakes: ["'닫힌 문'을 답으로 말하기(문제는 열린 문)", "처음 상태(모두 열림)를 닫힘으로 착각"],
    failReason: "시작 상태를 반대로 두면 답이 5개로 뒤바뀌어요(열림/닫힘 반전).",
    better: "30개를 다 시뮬레이션하지 않고 '제곱수'만 세면 즉시(√30<6 → 1²~5²).",
    other: "만약 처음 모두 '닫힘'이었다면 열린 문 = 제곱수 5개(고전 버전).",
    concept: "시뮬레이션, 약수·제곱수 성질, 규칙으로 예측, 실행과 예측 비교.",
    think: "문이 100개라면 닫힌 문은 몇 개일까요? (제곱수의 개수)",
  },
  learningGoals: ["시뮬레이션과 규칙 예측 비교", "약수/제곱수 성질"],
  curriculumTags: ["상태 표현", "반복 구조", "패턴과 일반화", "알고리즘 실행"],
  reflectionQuestions: ["왜 제곱수 문만 상태가 홀수 번 바뀌나요?"],
  answerSource: "book-and-verified",
  verificationMethod: "완전 시뮬레이션(30명×토글) + 약수 개수 홀짝 이론 대조(openDoorsSolver)",
  verificationEvidence: "시뮬레이션 열린 문 25개, 닫힌 문 {1,4,9,16,25}. 이론과 일치.",
  teacher: {
    origDifficulty: "레벨 3", allAnswers: ["열린 문 25개(닫힘=제곱수 5개)"], optimal: "제곱수 개수로 즉시",
    commonWrong: ["5개(시작 상태 반대로 봄)", "닫힌 문 개수를 답함"], wrongWhy: "시작 상태·질문 대상 혼동.",
    questions: ["문 d를 건드리는 사람은 누구누구인가?", "왜 제곱수만 다를까?"],
    intro: "실제 문(사물함) 상황으로 도입.",
    group: "모둠이 앞부분을 손으로 시뮬레이션 후 규칙 추측.",
    tune: "기초: 10개 문. 도전: 100개 문 예측.",
    programming: "이중 for로 토글 시뮬레이션 + 제곱수 판정 비교.",
    extension: ["100개·n개 일반화", "시작이 닫힘인 버전과 비교"],
    eval: "시뮬레이션 결과와 약수 규칙을 연결했는지 평가.", minutes: 8,
  },
});

PROBLEMS.push({
  id: "C-07", sourceProblem: "5-49", sourcePage: 111, world: "both",
  title: "폭탄 전략", engine: "nim", difficulty: "challenge", estimatedMinutes: 8,
  originalProblemText:
    "'폭탄 가져가기' 게임: 두 사람이 번갈아 폭탄을 가져가는데, 한 번에 1~3개까지 가져갈 수 있고, 맨 마지막 '빵' 폭탄을 가져가는 사람이 진다. 30개 폭탄에서 항상 이기는 전략을 설명하고, 먼저 하는 사람이 반드시 이기려면 처음에 몇 개를 가져가야 하는가?",
  studentFriendlyText:
    "폭탄 30개! 번갈아 1~3개씩 가져가고, 마지막 폭탄을 가져가는 사람이 져요.\n컴퓨터와 대결해요. 항상 이기는 규칙을 찾아보세요! (처음에 몇 개를 가져갈까?)",
  conditions: ["한 번에 1~3개", "번갈아 가져감", "마지막(30번째) 폭탄 가져가면 패배"],
  irrelevantInformation: ["폭탄 색·모양은 무관"],
  correctAnswers: ["1"], equivalentAnswers: ["처음에 1개", "1개"],
  config: {
    kind: "nim", total: 30, maxTake: 3, loseOnLast: true, winningFirstMove: 1,
  },
  hint1Observation: "마지막 폭탄을 상대가 가져가게 만들려면, 상대에게 몇 개를 '남겨' 주면 좋을까요?",
  hint2KeyCondition: "상대에게 남는 폭탄 수를 '4로 나눈 나머지'가 특정 값이 되게 만들면 유리해요.",
  hint3NextAction: "상대가 x개 가져가면 나는 (4−x)개를 가져가 한 라운드에 4개씩 줄여 보세요. 그러려면 첫 수를 어떻게 정할지 생각해요.",
  guidedSolution: [
    "지는 자리 = 내 차례에 남은 폭탄이 1,5,9,…,29(4로 나눠 1 남음)인 경우.",
    "그래서 상대를 그 자리로 몰아야 함.",
    "30개 → 먼저 1개 가져가 29개를 남긴다.",
    "이후 상대가 x개 가져가면 나는 (4−x)개 → 매 라운드 4개씩 줄어 25,21,…,1로 상대를 몰아붙임 → 승리.",
  ],
  fullExplanation: {
    answer: "먼저 1개를 가져가면 반드시 이긴다.",
    key: "합이 4가 되도록 되받아치기(상대 x → 나 4−x)로 '남은 수'를 조절.",
    abstraction: "남은 폭탄 수를 상태로 보고, '4로 나눈 나머지'로 승/패 자리를 판별.",
    steps: ["패배 자리 = 남은 수 ≡ 1 (mod 4)", "상대를 패배 자리로: 먼저 1개(→29)", "이후 4−x로 대응", "상대가 마지막을 잡게 됨"],
    why: ["한 라운드에 둘이 합쳐 최대 4개까지 가져가므로, 4의 주기로 자리를 고정할 수 있어요."],
    verify: "게임 트리(미니맥스)로 30·최대3·마지막패배는 선공 승리, 최적 첫 수=1임을 확인.",
    mistakes: ["처음에 3개를 가져가기(→27, 상대에게 유리)", "되받아치기(4−x)를 잊기"],
    failReason: "남은 수를 4의 나머지로 관리하지 않으면 상대가 주도권을 가져가요.",
    better: "일반식: 먼저 (남은수−1) mod (최대+1) 개를 가져간다. 여기선 (30−1) mod 4 = 1.",
    other: "'마지막을 가져가면 이김' 규칙이면 전략이 반대로 바뀌어요(남은 수 ≡ 0 mod 4로).",
    concept: "게임 트리, 상태(나머지)로 승패 판정, 선택 구조, 되받아치기 규칙.",
    think: "50개·최대 5개 버전이면 처음에 몇 개를 가져가야 할까요? (5-50)",
  },
  learningGoals: ["승리 상태(모듈러) 발견", "상대 행동에 대응하는 규칙", "게임 트리 사고"],
  curriculumTags: ["상태 표현", "선택 구조", "패턴과 일반화", "알고리즘 설계"],
  reflectionQuestions: ["'4−x로 되받아치기'가 왜 항상 통할까요?"],
  answerSource: "book-and-verified",
  verificationMethod: "미니맥스 게임 트리 + 모듈러 승패 이론 대조(strategySolver)",
  verificationEvidence: "선공 승리, 최적 첫 수 1. 컴퓨터 AI가 항상 최적 대응하도록 구현.",
  teacher: {
    origDifficulty: "레벨 3", allAnswers: ["처음에 1개(선공 필승)"], optimal: "1개",
    commonWrong: ["3개(직관적 최대)", "대응 규칙 미사용"], wrongWhy: "모듈러 구조 미인식.",
    questions: ["패배 자리는 어떤 수인가?", "한 라운드에 최대 몇 개가 사라지나?"],
    intro: "실제 바둑돌/블록으로 대결하며 규칙 감 잡기.",
    group: "모둠 대항전 후 필승 자리를 함께 정리.",
    tune: "기초: 폭탄 10개. 도전: 50개·최대 5개(5-50).",
    programming: "미니맥스 또는 (n−1)%(k+1) 공식으로 AI 구현.",
    extension: ["'마지막 가져가면 승리' 버전", "최대 개수·총 개수 바꾸기"],
    eval: "승리 상태를 찾고 대응 규칙을 설명했는지, AI를 이겼는지 평가.", minutes: 8,
  },
});
